// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/data_backup.dart';
import 'api/file_manager.dart';
import 'api/http.dart';
import 'api/image.dart';
import 'api/local.dart';
import 'api/local_thumbnail.dart';
import 'api/localization.dart';
import 'api/logger.dart';
import 'api/memory.dart';
import 'api/mimage_onnx.dart';
import 'api/operation_binding.dart';
import 'api/qjs.dart';
import 'api/simple.dart';
import 'api/system.dart';
import 'api/user_utils.dart';
import 'api/webdav.dart';
import 'compressed/compressed.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'decode/decode.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'qjs.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HttpClientPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClientPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LogHttpMakeWriterPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriterPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  HttpClient
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    dynamic raw,
  );

  @protected
  LogHttpMakeWriter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter(
    dynamic raw,
  );

  @protected
  HttpClient
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    dynamic raw,
  );

  @protected
  FutureOr<String> Function(String)
  dco_decode_DartFn_Inputs_String_Output_String_AnyhowException(dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, (int, int)> dco_decode_Map_String_record_u_32_u_32_None(
    dynamic raw,
  );

  @protected
  HttpClient
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    dynamic raw,
  );

  @protected
  LogHttpMakeWriter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<bool> dco_decode_StreamSink_bool_Sse(dynamic raw);

  @protected
  RustStreamSink<HttpProgress> dco_decode_StreamSink_http_progress_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  FetchInit dco_decode_box_autoadd_fetch_init(dynamic raw);

  @protected
  HttpClientOptions dco_decode_box_autoadd_http_client_options(dynamic raw);

  @protected
  ImageInfo dco_decode_box_autoadd_image_info(dynamic raw);

  @protected
  LocalDecodeFailure dco_decode_box_autoadd_local_decode_failure(dynamic raw);

  @protected
  LocalPagePixels dco_decode_box_autoadd_local_page_pixels(dynamic raw);

  @protected
  LocalRejection dco_decode_box_autoadd_local_rejection(dynamic raw);

  @protected
  LocalSourceInfo dco_decode_box_autoadd_local_source_info(dynamic raw);

  @protected
  PackInfo dco_decode_box_autoadd_pack_info(dynamic raw);

  @protected
  QjsRuntimeBuildRequest dco_decode_box_autoadd_qjs_runtime_build_request(
    dynamic raw,
  );

  @protected
  QjsRuntimeBundleBuild dco_decode_box_autoadd_qjs_runtime_bundle_build(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FetchInit dco_decode_fetch_init(dynamic raw);

  @protected
  FetchResponse dco_decode_fetch_response(dynamic raw);

  @protected
  FileManagerActionResult dco_decode_file_manager_action_result(dynamic raw);

  @protected
  FileManagerBreadcrumb dco_decode_file_manager_breadcrumb(dynamic raw);

  @protected
  FileManagerChild dco_decode_file_manager_child(dynamic raw);

  @protected
  FileManagerDirectoryChoice dco_decode_file_manager_directory_choice(
    dynamic raw,
  );

  @protected
  FileManagerDirectoryColumn dco_decode_file_manager_directory_column(
    dynamic raw,
  );

  @protected
  FileManagerEntry dco_decode_file_manager_entry(dynamic raw);

  @protected
  FileManagerEntryFilter dco_decode_file_manager_entry_filter(dynamic raw);

  @protected
  FileManagerInternalItemsMode dco_decode_file_manager_internal_items_mode(
    dynamic raw,
  );

  @protected
  FileManagerSnapshot dco_decode_file_manager_snapshot(dynamic raw);

  @protected
  FileManagerSortField dco_decode_file_manager_sort_field(dynamic raw);

  @protected
  FileManagerSortOrder dco_decode_file_manager_sort_order(dynamic raw);

  @protected
  FileManagerTab dco_decode_file_manager_tab(dynamic raw);

  @protected
  FileManagerTreeRow dco_decode_file_manager_tree_row(dynamic raw);

  @protected
  FileManagerTreeSnapshot dco_decode_file_manager_tree_snapshot(dynamic raw);

  @protected
  FileManagerViewMode dco_decode_file_manager_view_mode(dynamic raw);

  @protected
  HttpClientOptions dco_decode_http_client_options(dynamic raw);

  @protected
  HttpProgress dco_decode_http_progress(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageInfo dco_decode_image_info(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FileManagerBreadcrumb> dco_decode_list_file_manager_breadcrumb(
    dynamic raw,
  );

  @protected
  List<FileManagerChild> dco_decode_list_file_manager_child(dynamic raw);

  @protected
  List<FileManagerDirectoryChoice>
  dco_decode_list_file_manager_directory_choice(dynamic raw);

  @protected
  List<FileManagerDirectoryColumn>
  dco_decode_list_file_manager_directory_column(dynamic raw);

  @protected
  List<FileManagerEntry> dco_decode_list_file_manager_entry(dynamic raw);

  @protected
  List<FileManagerTab> dco_decode_list_file_manager_tab(dynamic raw);

  @protected
  List<FileManagerTreeRow> dco_decode_list_file_manager_tree_row(dynamic raw);

  @protected
  List<LocalFileTreeNode> dco_decode_list_local_file_tree_node(dynamic raw);

  @protected
  List<LocalPageInfo> dco_decode_list_local_page_info(dynamic raw);

  @protected
  List<LocalRootLocation> dco_decode_list_local_root_location(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, (int, int))> dco_decode_list_record_string_record_u_32_u_32(
    dynamic raw,
  );

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<TaggedAllocation> dco_decode_list_tagged_allocation(dynamic raw);

  @protected
  LocalDecodeFailure dco_decode_local_decode_failure(dynamic raw);

  @protected
  LocalDecodeFailureKind dco_decode_local_decode_failure_kind(dynamic raw);

  @protected
  LocalFileTreeNode dco_decode_local_file_tree_node(dynamic raw);

  @protected
  LocalPageDecodeResult dco_decode_local_page_decode_result(dynamic raw);

  @protected
  LocalPageInfo dco_decode_local_page_info(dynamic raw);

  @protected
  LocalPageLoadContract dco_decode_local_page_load_contract(dynamic raw);

  @protected
  LocalPageLoadPriority dco_decode_local_page_load_priority(dynamic raw);

  @protected
  LocalPageLoadStats dco_decode_local_page_load_stats(dynamic raw);

  @protected
  LocalPagePixels dco_decode_local_page_pixels(dynamic raw);

  @protected
  LocalPrefetchDecision dco_decode_local_prefetch_decision(dynamic raw);

  @protected
  LocalRejection dco_decode_local_rejection(dynamic raw);

  @protected
  LocalRejectionKind dco_decode_local_rejection_kind(dynamic raw);

  @protected
  LocalRootLocation dco_decode_local_root_location(dynamic raw);

  @protected
  LocalSourceInfo dco_decode_local_source_info(dynamic raw);

  @protected
  LocalSourceKind dco_decode_local_source_kind(dynamic raw);

  @protected
  LocalSourceOpenResult dco_decode_local_source_open_result(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  RustStreamSink<HttpProgress>? dco_decode_opt_StreamSink_http_progress_Sse(
    dynamic raw,
  );

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  FetchInit? dco_decode_opt_box_autoadd_fetch_init(dynamic raw);

  @protected
  HttpClientOptions? dco_decode_opt_box_autoadd_http_client_options(
    dynamic raw,
  );

  @protected
  LocalDecodeFailure? dco_decode_opt_box_autoadd_local_decode_failure(
    dynamic raw,
  );

  @protected
  LocalPagePixels? dco_decode_opt_box_autoadd_local_page_pixels(dynamic raw);

  @protected
  LocalRejection? dco_decode_opt_box_autoadd_local_rejection(dynamic raw);

  @protected
  LocalSourceInfo? dco_decode_opt_box_autoadd_local_source_info(dynamic raw);

  @protected
  QjsRuntimeBundleBuild? dco_decode_opt_box_autoadd_qjs_runtime_bundle_build(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PackInfo dco_decode_pack_info(dynamic raw);

  @protected
  QjsCancelTasksByGroupResult dco_decode_qjs_cancel_tasks_by_group_result(
    dynamic raw,
  );

  @protected
  QjsRuntimeBuildRequest dco_decode_qjs_runtime_build_request(dynamic raw);

  @protected
  QjsRuntimeBundleBuild dco_decode_qjs_runtime_bundle_build(dynamic raw);

  @protected
  (String, (int, int)) dco_decode_record_string_record_u_32_u_32(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (int, int) dco_decode_record_u_32_u_32(dynamic raw);

  @protected
  RustMemoryInfo dco_decode_rust_memory_info(dynamic raw);

  @protected
  TaggedAllocation dco_decode_tagged_allocation(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  HttpClient
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    SseDeserializer deserializer,
  );

  @protected
  LogHttpMakeWriter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter(
    SseDeserializer deserializer,
  );

  @protected
  HttpClient
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    SseDeserializer deserializer,
  );

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, (int, int)> sse_decode_Map_String_record_u_32_u_32_None(
    SseDeserializer deserializer,
  );

  @protected
  HttpClient
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    SseDeserializer deserializer,
  );

  @protected
  LogHttpMakeWriter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<bool> sse_decode_StreamSink_bool_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<HttpProgress> sse_decode_StreamSink_http_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  FetchInit sse_decode_box_autoadd_fetch_init(SseDeserializer deserializer);

  @protected
  HttpClientOptions sse_decode_box_autoadd_http_client_options(
    SseDeserializer deserializer,
  );

  @protected
  ImageInfo sse_decode_box_autoadd_image_info(SseDeserializer deserializer);

  @protected
  LocalDecodeFailure sse_decode_box_autoadd_local_decode_failure(
    SseDeserializer deserializer,
  );

  @protected
  LocalPagePixels sse_decode_box_autoadd_local_page_pixels(
    SseDeserializer deserializer,
  );

  @protected
  LocalRejection sse_decode_box_autoadd_local_rejection(
    SseDeserializer deserializer,
  );

  @protected
  LocalSourceInfo sse_decode_box_autoadd_local_source_info(
    SseDeserializer deserializer,
  );

  @protected
  PackInfo sse_decode_box_autoadd_pack_info(SseDeserializer deserializer);

  @protected
  QjsRuntimeBuildRequest sse_decode_box_autoadd_qjs_runtime_build_request(
    SseDeserializer deserializer,
  );

  @protected
  QjsRuntimeBundleBuild sse_decode_box_autoadd_qjs_runtime_bundle_build(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FetchInit sse_decode_fetch_init(SseDeserializer deserializer);

  @protected
  FetchResponse sse_decode_fetch_response(SseDeserializer deserializer);

  @protected
  FileManagerActionResult sse_decode_file_manager_action_result(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerBreadcrumb sse_decode_file_manager_breadcrumb(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerChild sse_decode_file_manager_child(SseDeserializer deserializer);

  @protected
  FileManagerDirectoryChoice sse_decode_file_manager_directory_choice(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerDirectoryColumn sse_decode_file_manager_directory_column(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerEntry sse_decode_file_manager_entry(SseDeserializer deserializer);

  @protected
  FileManagerEntryFilter sse_decode_file_manager_entry_filter(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerInternalItemsMode sse_decode_file_manager_internal_items_mode(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerSnapshot sse_decode_file_manager_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerSortField sse_decode_file_manager_sort_field(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerSortOrder sse_decode_file_manager_sort_order(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerTab sse_decode_file_manager_tab(SseDeserializer deserializer);

  @protected
  FileManagerTreeRow sse_decode_file_manager_tree_row(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerTreeSnapshot sse_decode_file_manager_tree_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  FileManagerViewMode sse_decode_file_manager_view_mode(
    SseDeserializer deserializer,
  );

  @protected
  HttpClientOptions sse_decode_http_client_options(
    SseDeserializer deserializer,
  );

  @protected
  HttpProgress sse_decode_http_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageInfo sse_decode_image_info(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FileManagerBreadcrumb> sse_decode_list_file_manager_breadcrumb(
    SseDeserializer deserializer,
  );

  @protected
  List<FileManagerChild> sse_decode_list_file_manager_child(
    SseDeserializer deserializer,
  );

  @protected
  List<FileManagerDirectoryChoice>
  sse_decode_list_file_manager_directory_choice(SseDeserializer deserializer);

  @protected
  List<FileManagerDirectoryColumn>
  sse_decode_list_file_manager_directory_column(SseDeserializer deserializer);

  @protected
  List<FileManagerEntry> sse_decode_list_file_manager_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<FileManagerTab> sse_decode_list_file_manager_tab(
    SseDeserializer deserializer,
  );

  @protected
  List<FileManagerTreeRow> sse_decode_list_file_manager_tree_row(
    SseDeserializer deserializer,
  );

  @protected
  List<LocalFileTreeNode> sse_decode_list_local_file_tree_node(
    SseDeserializer deserializer,
  );

  @protected
  List<LocalPageInfo> sse_decode_list_local_page_info(
    SseDeserializer deserializer,
  );

  @protected
  List<LocalRootLocation> sse_decode_list_local_root_location(
    SseDeserializer deserializer,
  );

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, (int, int))> sse_decode_list_record_string_record_u_32_u_32(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<TaggedAllocation> sse_decode_list_tagged_allocation(
    SseDeserializer deserializer,
  );

  @protected
  LocalDecodeFailure sse_decode_local_decode_failure(
    SseDeserializer deserializer,
  );

  @protected
  LocalDecodeFailureKind sse_decode_local_decode_failure_kind(
    SseDeserializer deserializer,
  );

  @protected
  LocalFileTreeNode sse_decode_local_file_tree_node(
    SseDeserializer deserializer,
  );

  @protected
  LocalPageDecodeResult sse_decode_local_page_decode_result(
    SseDeserializer deserializer,
  );

  @protected
  LocalPageInfo sse_decode_local_page_info(SseDeserializer deserializer);

  @protected
  LocalPageLoadContract sse_decode_local_page_load_contract(
    SseDeserializer deserializer,
  );

  @protected
  LocalPageLoadPriority sse_decode_local_page_load_priority(
    SseDeserializer deserializer,
  );

  @protected
  LocalPageLoadStats sse_decode_local_page_load_stats(
    SseDeserializer deserializer,
  );

  @protected
  LocalPagePixels sse_decode_local_page_pixels(SseDeserializer deserializer);

  @protected
  LocalPrefetchDecision sse_decode_local_prefetch_decision(
    SseDeserializer deserializer,
  );

  @protected
  LocalRejection sse_decode_local_rejection(SseDeserializer deserializer);

  @protected
  LocalRejectionKind sse_decode_local_rejection_kind(
    SseDeserializer deserializer,
  );

  @protected
  LocalRootLocation sse_decode_local_root_location(
    SseDeserializer deserializer,
  );

  @protected
  LocalSourceInfo sse_decode_local_source_info(SseDeserializer deserializer);

  @protected
  LocalSourceKind sse_decode_local_source_kind(SseDeserializer deserializer);

  @protected
  LocalSourceOpenResult sse_decode_local_source_open_result(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<HttpProgress>? sse_decode_opt_StreamSink_http_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  FetchInit? sse_decode_opt_box_autoadd_fetch_init(
    SseDeserializer deserializer,
  );

  @protected
  HttpClientOptions? sse_decode_opt_box_autoadd_http_client_options(
    SseDeserializer deserializer,
  );

  @protected
  LocalDecodeFailure? sse_decode_opt_box_autoadd_local_decode_failure(
    SseDeserializer deserializer,
  );

  @protected
  LocalPagePixels? sse_decode_opt_box_autoadd_local_page_pixels(
    SseDeserializer deserializer,
  );

  @protected
  LocalRejection? sse_decode_opt_box_autoadd_local_rejection(
    SseDeserializer deserializer,
  );

  @protected
  LocalSourceInfo? sse_decode_opt_box_autoadd_local_source_info(
    SseDeserializer deserializer,
  );

  @protected
  QjsRuntimeBundleBuild? sse_decode_opt_box_autoadd_qjs_runtime_bundle_build(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PackInfo sse_decode_pack_info(SseDeserializer deserializer);

  @protected
  QjsCancelTasksByGroupResult sse_decode_qjs_cancel_tasks_by_group_result(
    SseDeserializer deserializer,
  );

  @protected
  QjsRuntimeBuildRequest sse_decode_qjs_runtime_build_request(
    SseDeserializer deserializer,
  );

  @protected
  QjsRuntimeBundleBuild sse_decode_qjs_runtime_bundle_build(
    SseDeserializer deserializer,
  );

  @protected
  (String, (int, int)) sse_decode_record_string_record_u_32_u_32(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_record_u_32_u_32(SseDeserializer deserializer);

  @protected
  RustMemoryInfo sse_decode_rust_memory_info(SseDeserializer deserializer);

  @protected
  TaggedAllocation sse_decode_tagged_allocation(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    HttpClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter(
    LogHttpMakeWriter self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    HttpClient self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_String_Output_String_AnyhowException(
    FutureOr<String> Function(String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_record_u_32_u_32_None(
    Map<String, (int, int)> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    HttpClient self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter(
    LogHttpMakeWriter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bool_Sse(
    RustStreamSink<bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_http_progress_Sse(
    RustStreamSink<HttpProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fetch_init(
    FetchInit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_http_client_options(
    HttpClientOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_info(
    ImageInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_decode_failure(
    LocalDecodeFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_page_pixels(
    LocalPagePixels self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_rejection(
    LocalRejection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_local_source_info(
    LocalSourceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pack_info(
    PackInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qjs_runtime_build_request(
    QjsRuntimeBuildRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qjs_runtime_bundle_build(
    QjsRuntimeBundleBuild self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fetch_init(FetchInit self, SseSerializer serializer);

  @protected
  void sse_encode_fetch_response(FetchResponse self, SseSerializer serializer);

  @protected
  void sse_encode_file_manager_action_result(
    FileManagerActionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_breadcrumb(
    FileManagerBreadcrumb self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_child(
    FileManagerChild self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_directory_choice(
    FileManagerDirectoryChoice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_directory_column(
    FileManagerDirectoryColumn self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_entry(
    FileManagerEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_entry_filter(
    FileManagerEntryFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_internal_items_mode(
    FileManagerInternalItemsMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_snapshot(
    FileManagerSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_sort_field(
    FileManagerSortField self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_sort_order(
    FileManagerSortOrder self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_tab(
    FileManagerTab self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_tree_row(
    FileManagerTreeRow self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_tree_snapshot(
    FileManagerTreeSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_manager_view_mode(
    FileManagerViewMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_http_client_options(
    HttpClientOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_http_progress(HttpProgress self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_info(ImageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_manager_breadcrumb(
    List<FileManagerBreadcrumb> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_manager_child(
    List<FileManagerChild> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_manager_directory_choice(
    List<FileManagerDirectoryChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_manager_directory_column(
    List<FileManagerDirectoryColumn> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_manager_entry(
    List<FileManagerEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_manager_tab(
    List<FileManagerTab> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_manager_tree_row(
    List<FileManagerTreeRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_file_tree_node(
    List<LocalFileTreeNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_page_info(
    List<LocalPageInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_root_location(
    List<LocalRootLocation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_record_u_32_u_32(
    List<(String, (int, int))> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tagged_allocation(
    List<TaggedAllocation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_decode_failure(
    LocalDecodeFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_decode_failure_kind(
    LocalDecodeFailureKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_file_tree_node(
    LocalFileTreeNode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_page_decode_result(
    LocalPageDecodeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_page_info(LocalPageInfo self, SseSerializer serializer);

  @protected
  void sse_encode_local_page_load_contract(
    LocalPageLoadContract self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_page_load_priority(
    LocalPageLoadPriority self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_page_load_stats(
    LocalPageLoadStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_page_pixels(
    LocalPagePixels self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_prefetch_decision(
    LocalPrefetchDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_rejection(
    LocalRejection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_rejection_kind(
    LocalRejectionKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_root_location(
    LocalRootLocation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_source_info(
    LocalSourceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_source_kind(
    LocalSourceKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_source_open_result(
    LocalSourceOpenResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_StreamSink_http_progress_Sse(
    RustStreamSink<HttpProgress>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_fetch_init(
    FetchInit? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_http_client_options(
    HttpClientOptions? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_local_decode_failure(
    LocalDecodeFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_local_page_pixels(
    LocalPagePixels? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_local_rejection(
    LocalRejection? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_local_source_info(
    LocalSourceInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_qjs_runtime_bundle_build(
    QjsRuntimeBundleBuild? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pack_info(PackInfo self, SseSerializer serializer);

  @protected
  void sse_encode_qjs_cancel_tasks_by_group_result(
    QjsCancelTasksByGroupResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qjs_runtime_build_request(
    QjsRuntimeBuildRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qjs_runtime_bundle_build(
    QjsRuntimeBundleBuild self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_record_u_32_u_32(
    (String, (int, int)) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_u_32((int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_rust_memory_info(
    RustMemoryInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tagged_allocation(
    TaggedAllocation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_zephyr_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClientPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_zephyr_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClient =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHttpClientPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_zephyr_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriterPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriterPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_zephyr_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriter =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogHttpMakeWriterPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
