// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../local.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

Future<BigInt> fileManagerCreate({
  String? initialPath,
  String? homePath,
  String? settingsDbPath,
  required bool rememberViewState,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerCreate(
  initialPath: initialPath,
  homePath: homePath,
  settingsDbPath: settingsDbPath,
  rememberViewState: rememberViewState,
);

Future<FileManagerSnapshot> fileManagerSnapshot({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerBrowseFileManagerSnapshot(id: id);

Future<FileManagerSnapshot> fileManagerRefresh({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerBrowseFileManagerRefresh(id: id);

Future<FileManagerSnapshot> fileManagerNavigate({
  required BigInt id,
  required String path,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerNavigate(
  id: id,
  path: path,
);

Future<FileManagerSnapshot> fileManagerNavigateText({
  required BigInt id,
  required String text,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerNavigateText(
  id: id,
  text: text,
);

Future<FileManagerSnapshot> fileManagerSetDirectoryColumns({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api
    .crateApiFileManagerBrowseFileManagerSetDirectoryColumns(
      id: id,
      enabled: enabled,
    );

Future<FileManagerSnapshot> fileManagerGoBack({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerBrowseFileManagerGoBack(id: id);

Future<FileManagerSnapshot> fileManagerGoForward({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerBrowseFileManagerGoForward(id: id);

Future<FileManagerSnapshot> fileManagerGoUp({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerBrowseFileManagerGoUp(id: id);

/// 跳回用户指定的主页。主页就是普通目录，因此同样进入页签的后退栈。
Future<FileManagerSnapshot> fileManagerGoHome({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerBrowseFileManagerGoHome(id: id);

/// 写入主页（`None` 清除）。核心只接受存在的目录，非法路径保持原值。
Future<FileManagerSnapshot> fileManagerSetHomePath({
  required BigInt id,
  String? path,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerSetHomePath(
  id: id,
  path: path,
);

Future<FileManagerSnapshot> fileManagerNewTab({
  required BigInt id,
  String? path,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerNewTab(
  id: id,
  path: path,
);

Future<FileManagerSnapshot> fileManagerActivateTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerActivateTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerCloseTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerDuplicateTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerDuplicateTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerToggleTabPinned({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerToggleTabPinned(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseOtherTabs({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerCloseOtherTabs(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseTabsLeft({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerCloseTabsLeft(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseTabsRight({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerCloseTabsRight(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerReopenClosedTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerBrowseFileManagerReopenClosedTab(
  id: id,
  tabId: tabId,
);
