// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../local.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<FileManagerActionResult> fileManagerOpenEntry({
  required BigInt id,
  required String path,
  required bool forceEnter,
}) => RustLib.instance.api.crateApiFileManagerEntryOpsFileManagerOpenEntry(
  id: id,
  path: path,
  forceEnter: forceEnter,
);

/// Open an archive from a double-click without changing the browser location.
///
/// The core validates the path with mImageViewer's archive predicates, so every
/// UI gets the same ZIP/CBZ/RAR/7z/LZH handling and cannot accidentally route a
/// normal file through the archive gesture.
Future<FileManagerActionResult> fileManagerOpenArchive({
  required BigInt id,
  required String path,
}) => RustLib.instance.api.crateApiFileManagerEntryOpsFileManagerOpenArchive(
  id: id,
  path: path,
);

/// 按打开时的列表与目录栈查找上下本；不依赖仍在挂载的文件管理器。
Future<LocalBookNavigationTarget?> localBookAdjacent({
  required String path,
  String? navigationJson,
  required bool forward,
}) => RustLib.instance.api.crateApiFileManagerEntryOpsLocalBookAdjacent(
  path: path,
  navigationJson: navigationJson,
  forward: forward,
);

class LocalBookNavigationTarget {
  final String path;
  final String navigationJson;

  const LocalBookNavigationTarget({
    required this.path,
    required this.navigationJson,
  });

  @override
  int get hashCode => path.hashCode ^ navigationJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalBookNavigationTarget &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          navigationJson == other.navigationJson;
}
