// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../local.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `load_search_history`, `map_search_outcome`, `now_secs`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FileManagerSearchGuard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

Future<FileManagerSnapshot> fileManagerSetSearchQuery({
  required BigInt id,
  required String query,
}) => RustLib.instance.api.crateApiFileManagerSearchFileManagerSetSearchQuery(
  id: id,
  query: query,
);

Future<FileManagerSnapshot> fileManagerSetSearchInPath({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerSearchFileManagerSetSearchInPath(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetSearchOrMode({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerSearchFileManagerSetSearchOrMode(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetSearchIncludeSubfolders({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api
    .crateApiFileManagerSearchFileManagerSetSearchIncludeSubfolders(
      id: id,
      enabled: enabled,
    );

Future<FileManagerSnapshot> fileManagerSetSearchMaxDepth({
  required BigInt id,
  required int depth,
}) =>
    RustLib.instance.api.crateApiFileManagerSearchFileManagerSetSearchMaxDepth(
      id: id,
      depth: depth,
    );

/// 按当前生效的搜索条件跑一次递归搜索。
///
/// 遍历**不**在 `with_session` 里跑：那个闭包握着会话的写锁，一次整库扫描会把
/// 其它卡片动作全部堵住。所以先取一份请求值（根路径 + 设置快照），再在阻塞线程
/// 上离线遍历。代价是遍历期间用户改设置不生效 —— 那本来就该由下一次搜索回答。
Future<FileManagerSnapshot> fileManagerSearch({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerSearchFileManagerSearch(id: id);

/// 把当前搜索结果另存成一个页签（NeoView 的「保存搜索到页签」）。
Future<FileManagerSnapshot> fileManagerSaveSearchAsTab({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerSearchFileManagerSaveSearchAsTab(
      id: id,
    );

/// 退出搜索结果视图，回到页签自己那一层目录（不清空搜索词）。
Future<FileManagerSnapshot> fileManagerClearSearch({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerSearchFileManagerClearSearch(
      id: id,
    );

/// 请求中止本会话正在跑的搜索。没有搜索在跑时是空操作。
Future<bool> fileManagerCancelSearch({required BigInt id}) => RustLib
    .instance
    .api
    .crateApiFileManagerSearchFileManagerCancelSearch(id: id);

/// 记一次搜索到历史里，并回给最新的列表（省得 Dart 再问一次）。
///
/// 设置库没打开时返回空列表而**不是**报错：历史是辅助信息，一次 SQLite 不可用
/// 不该让搜索框冒红。真正的搜索早已独立完成。
Future<List<String>> fileManagerRecordSearchHistory({required String query}) =>
    RustLib.instance.api
        .crateApiFileManagerSearchFileManagerRecordSearchHistory(query: query);

Future<List<String>> fileManagerSearchHistory({required int limit}) => RustLib
    .instance
    .api
    .crateApiFileManagerSearchFileManagerSearchHistory(limit: limit);

Future<int> fileManagerClearSearchHistory() => RustLib.instance.api
    .crateApiFileManagerSearchFileManagerClearSearchHistory();
