// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../local.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

Future<FileManagerSnapshot> fileManagerSetPenetration({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerSettingsFileManagerSetPenetration(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetShowChildNames({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api
    .crateApiFileManagerSettingsFileManagerSetShowChildNames(
      id: id,
      enabled: enabled,
    );

Future<FileManagerSnapshot> fileManagerSetInternalItemsMode({
  required BigInt id,
  required FileManagerInternalItemsMode mode,
}) => RustLib.instance.api
    .crateApiFileManagerSettingsFileManagerSetInternalItemsMode(
      id: id,
      mode: mode,
    );

Future<FileManagerSnapshot> fileManagerSetMaxDepth({
  required BigInt id,
  required int depth,
}) => RustLib.instance.api.crateApiFileManagerSettingsFileManagerSetMaxDepth(
  id: id,
  depth: depth,
);

Future<FileManagerSnapshot> fileManagerSetViewMode({
  required BigInt id,
  required FileManagerViewMode mode,
}) => RustLib.instance.api.crateApiFileManagerSettingsFileManagerSetViewMode(
  id: id,
  mode: mode,
);

Future<FileManagerSnapshot> fileManagerSetShowHiddenFiles({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api
    .crateApiFileManagerSettingsFileManagerSetShowHiddenFiles(
      id: id,
      enabled: enabled,
    );

Future<FileManagerSnapshot> fileManagerSetEntryFilter({
  required BigInt id,
  required FileManagerEntryFilter filter,
}) => RustLib.instance.api.crateApiFileManagerSettingsFileManagerSetEntryFilter(
  id: id,
  filter: filter,
);

Future<FileManagerSnapshot> fileManagerSetSort({
  required BigInt id,
  required FileManagerSortField field,
  required FileManagerSortOrder order,
}) => RustLib.instance.api.crateApiFileManagerSettingsFileManagerSetSort(
  id: id,
  field: field,
  order: order,
);

/// 工具栏的「锁定当前目录排序／取消临时排序」。
Future<FileManagerSnapshot> fileManagerSetSortTemporary({
  required BigInt id,
  required bool enabled,
}) =>
    RustLib.instance.api.crateApiFileManagerSettingsFileManagerSetSortTemporary(
      id: id,
      enabled: enabled,
    );

/// 「记住每个目录的视图与排序」总开关（对应全局设置里那一项）。
///
/// 置为 false 之后本会话既不读也不写目录偏好；已经存下来的行**不删**，
/// 所以重新打开开关就能恢复，与 mImageViewer 的 `remember_favorite_view_state` 同口径。
Future<FileManagerSnapshot> fileManagerSetRememberViewState({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api
    .crateApiFileManagerSettingsFileManagerSetRememberViewState(
      id: id,
      enabled: enabled,
    );

Future<FileManagerSnapshot> fileManagerSetDirectoriesFirst({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api
    .crateApiFileManagerSettingsFileManagerSetDirectoriesFirst(
      id: id,
      enabled: enabled,
    );

bool fileManagerClose({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerSettingsFileManagerClose(id: id);
