// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `with_pane`

Future<FileManagerTreeSnapshot> fileManagerTreeSnapshot({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerTreeFileManagerTreeSnapshot(id: id);

/// 展开/收起某一行。核心没有「按路径直接改展开态」的入口，于是把游标挪过去、
/// 再走键盘的左/右键 —— 与用户用方向键操作时是同一条路径，展开状态（`user_expanded`
/// / `user_collapsed`）的记账因此只有一套。
Future<FileManagerTreeSnapshot> fileManagerTreeToggle({
  required BigInt id,
  required String path,
}) => RustLib.instance.api.crateApiFileManagerTreeFileManagerTreeToggle(
  id: id,
  path: path,
);
