// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../local.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class FileManagerActionResult {
  final FileManagerSnapshot snapshot;

  /// 非空时表示 UI 应该把该路径交给 Reader；浏览器自身仍停留在原目录。
  final String? openedPath;

  /// 核心拥有的上下本游标；UI 只需随阅读目标透传。
  final String? bookNavigationJson;

  const FileManagerActionResult({
    required this.snapshot,
    this.openedPath,
    this.bookNavigationJson,
  });

  @override
  int get hashCode =>
      snapshot.hashCode ^ openedPath.hashCode ^ bookNavigationJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerActionResult &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          openedPath == other.openedPath &&
          bookNavigationJson == other.bookNavigationJson;
}

class FileManagerBreadcrumb {
  final String path;
  final String name;
  final bool isRoot;
  final bool isCurrent;

  const FileManagerBreadcrumb({
    required this.path,
    required this.name,
    required this.isRoot,
    required this.isCurrent,
  });

  @override
  int get hashCode =>
      path.hashCode ^ name.hashCode ^ isRoot.hashCode ^ isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerBreadcrumb &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isRoot == other.isRoot &&
          isCurrent == other.isCurrent;
}

class FileManagerChild {
  final String path;
  final String name;
  final bool isDir;
  final bool isArchive;
  final bool isImage;
  final bool isVideo;
  final bool isAudio;

  const FileManagerChild({
    required this.path,
    required this.name,
    required this.isDir,
    required this.isArchive,
    required this.isImage,
    required this.isVideo,
    required this.isAudio,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      isDir.hashCode ^
      isArchive.hashCode ^
      isImage.hashCode ^
      isVideo.hashCode ^
      isAudio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerChild &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isDir == other.isDir &&
          isArchive == other.isArchive &&
          isImage == other.isImage &&
          isVideo == other.isVideo &&
          isAudio == other.isAudio;
}

class FileManagerDirectoryChoice {
  final String path;
  final String name;
  final bool selected;

  const FileManagerDirectoryChoice({
    required this.path,
    required this.name,
    required this.selected,
  });

  @override
  int get hashCode => path.hashCode ^ name.hashCode ^ selected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerDirectoryChoice &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          selected == other.selected;
}

class FileManagerDirectoryColumn {
  final String path;
  final String name;
  final List<FileManagerDirectoryChoice> entries;
  final String? error;

  const FileManagerDirectoryColumn({
    required this.path,
    required this.name,
    required this.entries,
    this.error,
  });

  @override
  int get hashCode =>
      path.hashCode ^ name.hashCode ^ entries.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerDirectoryColumn &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          entries == other.entries &&
          error == other.error;
}

class FileManagerEntry {
  final String path;
  final String name;
  final bool isDir;
  final bool isArchive;
  final bool isImage;
  final bool isVideo;
  final bool isAudio;
  final BigInt size;
  final PlatformInt64 modifiedSecs;
  final bool hasChildren;

  /// NeoView 的「显示内部条目」投影。它不改变父目录列表，只为 UI 提供一小段
  /// 可点击的上下文提示。
  final List<FileManagerChild> childNames;

  /// 搜索结果页签里，这条命中在搜索根之下的目录（`/` 分隔）。普通浏览时为 `None`
  /// —— 那时父目录就是当前目录，写出来只是噪音。
  final String? searchDirectory;

  const FileManagerEntry({
    required this.path,
    required this.name,
    required this.isDir,
    required this.isArchive,
    required this.isImage,
    required this.isVideo,
    required this.isAudio,
    required this.size,
    required this.modifiedSecs,
    required this.hasChildren,
    required this.childNames,
    this.searchDirectory,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      isDir.hashCode ^
      isArchive.hashCode ^
      isImage.hashCode ^
      isVideo.hashCode ^
      isAudio.hashCode ^
      size.hashCode ^
      modifiedSecs.hashCode ^
      hasChildren.hashCode ^
      childNames.hashCode ^
      searchDirectory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isDir == other.isDir &&
          isArchive == other.isArchive &&
          isImage == other.isImage &&
          isVideo == other.isVideo &&
          isAudio == other.isAudio &&
          size == other.size &&
          modifiedSecs == other.modifiedSecs &&
          hasChildren == other.hasChildren &&
          childNames == other.childNames &&
          searchDirectory == other.searchDirectory;
}

enum FileManagerEntryFilter { all, folders, archives, images, video, audio }

enum FileManagerInternalItemsMode { single, all }

class FileManagerSnapshot {
  final BigInt sessionId;
  final int maxTabs;
  final bool canCreateTab;
  final BigInt generation;
  final BigInt activeTabId;
  final String activePath;
  final bool canGoUp;
  final List<FileManagerBreadcrumb> breadcrumbs;
  final bool directoryColumnsEnabled;
  final List<FileManagerDirectoryColumn> directoryColumns;
  final List<FileManagerTab> tabs;
  final List<FileManagerTab> recentlyClosed;
  final List<FileManagerEntry> entries;
  final List<LocalRootLocation> roots;
  final bool penetrationEnabled;
  final bool showChildNames;
  final FileManagerInternalItemsMode internalItemsMode;
  final int maxDepth;
  final FileManagerViewMode viewMode;
  final bool showHiddenFiles;
  final String searchQuery;

  /// 名称之外是否连同「相对搜索根的路径」一起匹配。
  final bool searchInPath;

  /// 多个词元的结合方式（false = AND，true = OR）。
  final bool searchOrMode;

  /// 递归搜索是否连同子目录。关掉时 `search_max_depth` 不参与。
  final bool searchIncludeSubfolders;

  /// 递归层数上限（实际生效值再被核心的 `MAX_SEARCH_DEPTH` 夹一次）。
  final int searchMaxDepth;

  /// 当前页签是不是「搜索结果页签」：列表画的是上一次遍历的命中，而不是目录。
  final bool searchActive;

  /// 这批命中对应的查询（说明文案与页签标题用）。
  final String searchResultQuery;

  /// 检视过的条目数（含未命中）。区分「没有」与「还没扫到」。
  final int searchScanned;

  /// 命中总数，可能因上限截断而大于列表长度。
  final int searchMatched;
  final bool searchTruncated;
  final bool searchCancelled;

  /// 「把当前搜索存成页签」是否可用（需要有结果）。
  final bool canSaveSearchTab;
  final FileManagerEntryFilter entryFilter;
  final FileManagerSortField sortField;
  final FileManagerSortOrder sortOrder;
  final bool directoriesFirst;

  /// 用户指定的主页；`None` 时工具栏的主页键应禁用。
  final String? homePath;
  final bool isHome;
  final bool canSetHome;

  /// 「临时排序」：排序变更不写回当前目录的视图状态。
  final bool sortTemporary;

  /// 目录级排序偏好是否可用（`remember_view_state`）。
  final bool canSortPreference;

  /// 「记住每个目录的视图与排序」总开关的当前值。关闭时本会话不读不写目录偏好。
  final bool rememberViewState;

  const FileManagerSnapshot({
    required this.sessionId,
    required this.maxTabs,
    required this.canCreateTab,
    required this.generation,
    required this.activeTabId,
    required this.activePath,
    required this.canGoUp,
    required this.breadcrumbs,
    required this.directoryColumnsEnabled,
    required this.directoryColumns,
    required this.tabs,
    required this.recentlyClosed,
    required this.entries,
    required this.roots,
    required this.penetrationEnabled,
    required this.showChildNames,
    required this.internalItemsMode,
    required this.maxDepth,
    required this.viewMode,
    required this.showHiddenFiles,
    required this.searchQuery,
    required this.searchInPath,
    required this.searchOrMode,
    required this.searchIncludeSubfolders,
    required this.searchMaxDepth,
    required this.searchActive,
    required this.searchResultQuery,
    required this.searchScanned,
    required this.searchMatched,
    required this.searchTruncated,
    required this.searchCancelled,
    required this.canSaveSearchTab,
    required this.entryFilter,
    required this.sortField,
    required this.sortOrder,
    required this.directoriesFirst,
    this.homePath,
    required this.isHome,
    required this.canSetHome,
    required this.sortTemporary,
    required this.canSortPreference,
    required this.rememberViewState,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      maxTabs.hashCode ^
      canCreateTab.hashCode ^
      generation.hashCode ^
      activeTabId.hashCode ^
      activePath.hashCode ^
      canGoUp.hashCode ^
      breadcrumbs.hashCode ^
      directoryColumnsEnabled.hashCode ^
      directoryColumns.hashCode ^
      tabs.hashCode ^
      recentlyClosed.hashCode ^
      entries.hashCode ^
      roots.hashCode ^
      penetrationEnabled.hashCode ^
      showChildNames.hashCode ^
      internalItemsMode.hashCode ^
      maxDepth.hashCode ^
      viewMode.hashCode ^
      showHiddenFiles.hashCode ^
      searchQuery.hashCode ^
      searchInPath.hashCode ^
      searchOrMode.hashCode ^
      searchIncludeSubfolders.hashCode ^
      searchMaxDepth.hashCode ^
      searchActive.hashCode ^
      searchResultQuery.hashCode ^
      searchScanned.hashCode ^
      searchMatched.hashCode ^
      searchTruncated.hashCode ^
      searchCancelled.hashCode ^
      canSaveSearchTab.hashCode ^
      entryFilter.hashCode ^
      sortField.hashCode ^
      sortOrder.hashCode ^
      directoriesFirst.hashCode ^
      homePath.hashCode ^
      isHome.hashCode ^
      canSetHome.hashCode ^
      sortTemporary.hashCode ^
      canSortPreference.hashCode ^
      rememberViewState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerSnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          maxTabs == other.maxTabs &&
          canCreateTab == other.canCreateTab &&
          generation == other.generation &&
          activeTabId == other.activeTabId &&
          activePath == other.activePath &&
          canGoUp == other.canGoUp &&
          breadcrumbs == other.breadcrumbs &&
          directoryColumnsEnabled == other.directoryColumnsEnabled &&
          directoryColumns == other.directoryColumns &&
          tabs == other.tabs &&
          recentlyClosed == other.recentlyClosed &&
          entries == other.entries &&
          roots == other.roots &&
          penetrationEnabled == other.penetrationEnabled &&
          showChildNames == other.showChildNames &&
          internalItemsMode == other.internalItemsMode &&
          maxDepth == other.maxDepth &&
          viewMode == other.viewMode &&
          showHiddenFiles == other.showHiddenFiles &&
          searchQuery == other.searchQuery &&
          searchInPath == other.searchInPath &&
          searchOrMode == other.searchOrMode &&
          searchIncludeSubfolders == other.searchIncludeSubfolders &&
          searchMaxDepth == other.searchMaxDepth &&
          searchActive == other.searchActive &&
          searchResultQuery == other.searchResultQuery &&
          searchScanned == other.searchScanned &&
          searchMatched == other.searchMatched &&
          searchTruncated == other.searchTruncated &&
          searchCancelled == other.searchCancelled &&
          canSaveSearchTab == other.canSaveSearchTab &&
          entryFilter == other.entryFilter &&
          sortField == other.sortField &&
          sortOrder == other.sortOrder &&
          directoriesFirst == other.directoriesFirst &&
          homePath == other.homePath &&
          isHome == other.isHome &&
          canSetHome == other.canSetHome &&
          sortTemporary == other.sortTemporary &&
          canSortPreference == other.canSortPreference &&
          rememberViewState == other.rememberViewState;
}

enum FileManagerSortField { name, type, size, date, random }

enum FileManagerSortOrder { ascending, descending }

class FileManagerTab {
  final BigInt id;
  final String title;
  final String path;
  final bool canGoBack;
  final bool canGoForward;
  final bool pinned;
  final bool canClose;
  final bool canCloseOthers;
  final bool canCloseLeft;
  final bool canCloseRight;

  const FileManagerTab({
    required this.id,
    required this.title,
    required this.path,
    required this.canGoBack,
    required this.canGoForward,
    required this.pinned,
    required this.canClose,
    required this.canCloseOthers,
    required this.canCloseLeft,
    required this.canCloseRight,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      path.hashCode ^
      canGoBack.hashCode ^
      canGoForward.hashCode ^
      pinned.hashCode ^
      canClose.hashCode ^
      canCloseOthers.hashCode ^
      canCloseLeft.hashCode ^
      canCloseRight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerTab &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          path == other.path &&
          canGoBack == other.canGoBack &&
          canGoForward == other.canGoForward &&
          pinned == other.pinned &&
          canClose == other.canClose &&
          canCloseOthers == other.canCloseOthers &&
          canCloseLeft == other.canCloseLeft &&
          canCloseRight == other.canCloseRight;
}

/// 文件树的一行：核心 `FolderPaneRow` 的字符串投影。
class FileManagerTreeRow {
  final String path;
  final String name;
  final int depth;
  final bool expanded;

  /// 子目录正在后台枚举：这一行的箭头该转圈。
  final bool loading;

  /// 「有子目录，或者还没查过」。确认是空目录时 UI 才收起箭头。
  final bool mayHaveChildren;
  final bool isActive;
  final String? error;

  const FileManagerTreeRow({
    required this.path,
    required this.name,
    required this.depth,
    required this.expanded,
    required this.loading,
    required this.mayHaveChildren,
    required this.isActive,
    this.error,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      depth.hashCode ^
      expanded.hashCode ^
      loading.hashCode ^
      mayHaveChildren.hashCode ^
      isActive.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerTreeRow &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          depth == other.depth &&
          expanded == other.expanded &&
          loading == other.loading &&
          mayHaveChildren == other.mayHaveChildren &&
          isActive == other.isActive &&
          error == other.error;
}

class FileManagerTreeSnapshot {
  final List<FileManagerTreeRow> rows;

  /// 仍有目录在枚举中。UI 据此决定要不要隔一会儿再问一次。
  final bool hasPending;

  const FileManagerTreeSnapshot({required this.rows, required this.hasPending});

  @override
  int get hashCode => rows.hashCode ^ hasPending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerTreeSnapshot &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          hasPending == other.hasPending;
}

enum FileManagerViewMode {
  compact,
  coverList,
  mosaicList,
  details,
  coverGrid,
  mosaicGrid,
}
