// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'local.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_session_operation`, `map_entry`, `snapshot_for`, `with_session`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FILE_MANAGER_SESSIONS`, `NEXT_FILE_MANAGER_ID`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `deref`, `deref`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`, `initialize`

Future<BigInt> fileManagerCreate({String? initialPath}) => RustLib.instance.api
    .crateApiFileManagerFileManagerCreate(initialPath: initialPath);

Future<FileManagerSnapshot> fileManagerSnapshot({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerSnapshot(id: id);

Future<FileManagerSnapshot> fileManagerRefresh({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerRefresh(id: id);

Future<FileManagerSnapshot> fileManagerNavigate({
  required BigInt id,
  required String path,
}) => RustLib.instance.api.crateApiFileManagerFileManagerNavigate(
  id: id,
  path: path,
);

Future<FileManagerSnapshot> fileManagerNavigateText({
  required BigInt id,
  required String text,
}) => RustLib.instance.api.crateApiFileManagerFileManagerNavigateText(
  id: id,
  text: text,
);

Future<FileManagerSnapshot> fileManagerSetDirectoryColumns({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetDirectoryColumns(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerGoBack({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerGoBack(id: id);

Future<FileManagerSnapshot> fileManagerGoForward({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerGoForward(id: id);

Future<FileManagerSnapshot> fileManagerGoUp({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerGoUp(id: id);

Future<FileManagerSnapshot> fileManagerNewTab({
  required BigInt id,
  String? path,
}) => RustLib.instance.api.crateApiFileManagerFileManagerNewTab(
  id: id,
  path: path,
);

Future<FileManagerSnapshot> fileManagerActivateTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerActivateTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerCloseTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerDuplicateTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerDuplicateTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerToggleTabPinned({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerToggleTabPinned(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseOtherTabs({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerCloseOtherTabs(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseTabsLeft({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerCloseTabsLeft(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseTabsRight({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerCloseTabsRight(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerReopenClosedTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerReopenClosedTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerActionResult> fileManagerOpenEntry({
  required BigInt id,
  required String path,
  required bool forceEnter,
}) => RustLib.instance.api.crateApiFileManagerFileManagerOpenEntry(
  id: id,
  path: path,
  forceEnter: forceEnter,
);

/// Open an archive from a double-click without changing the browser location.
///
/// The core validates the path with mImageViewer's archive predicates, so every
/// UI gets the same ZIP/CBZ/RAR/7z/LZH handling and cannot accidentally route a
/// normal file through the archive gesture.
Future<FileManagerActionResult> fileManagerOpenArchive({
  required BigInt id,
  required String path,
}) => RustLib.instance.api.crateApiFileManagerFileManagerOpenArchive(
  id: id,
  path: path,
);

Future<FileManagerSnapshot> fileManagerSetPenetration({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetPenetration(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetShowChildNames({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetShowChildNames(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetInternalItemsMode({
  required BigInt id,
  required FileManagerInternalItemsMode mode,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetInternalItemsMode(
  id: id,
  mode: mode,
);

Future<FileManagerSnapshot> fileManagerSetMaxDepth({
  required BigInt id,
  required int depth,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetMaxDepth(
  id: id,
  depth: depth,
);

Future<FileManagerSnapshot> fileManagerSetViewMode({
  required BigInt id,
  required FileManagerViewMode mode,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetViewMode(
  id: id,
  mode: mode,
);

Future<FileManagerSnapshot> fileManagerSetShowHiddenFiles({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetShowHiddenFiles(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetSearchQuery({
  required BigInt id,
  required String query,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetSearchQuery(
  id: id,
  query: query,
);

Future<FileManagerSnapshot> fileManagerSetEntryFilter({
  required BigInt id,
  required FileManagerEntryFilter filter,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetEntryFilter(
  id: id,
  filter: filter,
);

Future<FileManagerSnapshot> fileManagerSetSort({
  required BigInt id,
  required FileManagerSortField field,
  required FileManagerSortOrder order,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetSort(
  id: id,
  field: field,
  order: order,
);

Future<FileManagerSnapshot> fileManagerSetDirectoriesFirst({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetDirectoriesFirst(
  id: id,
  enabled: enabled,
);

bool fileManagerClose({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerClose(id: id);

class FileManagerActionResult {
  final FileManagerSnapshot snapshot;

  /// 非空时表示 UI 应该把该路径交给 Reader；浏览器自身仍停留在原目录。
  final String? openedPath;

  const FileManagerActionResult({required this.snapshot, this.openedPath});

  @override
  int get hashCode => snapshot.hashCode ^ openedPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerActionResult &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          openedPath == other.openedPath;
}

class FileManagerBreadcrumb {
  final String path;
  final String name;
  final bool isRoot;
  final bool isCurrent;

  const FileManagerBreadcrumb({
    required this.path,
    required this.name,
    required this.isRoot,
    required this.isCurrent,
  });

  @override
  int get hashCode =>
      path.hashCode ^ name.hashCode ^ isRoot.hashCode ^ isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerBreadcrumb &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isRoot == other.isRoot &&
          isCurrent == other.isCurrent;
}

class FileManagerChild {
  final String path;
  final String name;
  final bool isDir;
  final bool isArchive;
  final bool isImage;
  final bool isVideo;
  final bool isAudio;

  const FileManagerChild({
    required this.path,
    required this.name,
    required this.isDir,
    required this.isArchive,
    required this.isImage,
    required this.isVideo,
    required this.isAudio,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      isDir.hashCode ^
      isArchive.hashCode ^
      isImage.hashCode ^
      isVideo.hashCode ^
      isAudio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerChild &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isDir == other.isDir &&
          isArchive == other.isArchive &&
          isImage == other.isImage &&
          isVideo == other.isVideo &&
          isAudio == other.isAudio;
}

class FileManagerDirectoryChoice {
  final String path;
  final String name;
  final bool selected;

  const FileManagerDirectoryChoice({
    required this.path,
    required this.name,
    required this.selected,
  });

  @override
  int get hashCode => path.hashCode ^ name.hashCode ^ selected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerDirectoryChoice &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          selected == other.selected;
}

class FileManagerDirectoryColumn {
  final String path;
  final String name;
  final List<FileManagerDirectoryChoice> entries;
  final String? error;

  const FileManagerDirectoryColumn({
    required this.path,
    required this.name,
    required this.entries,
    this.error,
  });

  @override
  int get hashCode =>
      path.hashCode ^ name.hashCode ^ entries.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerDirectoryColumn &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          entries == other.entries &&
          error == other.error;
}

class FileManagerEntry {
  final String path;
  final String name;
  final bool isDir;
  final bool isArchive;
  final bool isImage;
  final bool isVideo;
  final bool isAudio;
  final BigInt size;
  final bool hasChildren;

  /// NeoView 的「显示内部条目」投影。它不改变父目录列表，只为 UI 提供一小段
  /// 可点击的上下文提示。
  final List<FileManagerChild> childNames;

  const FileManagerEntry({
    required this.path,
    required this.name,
    required this.isDir,
    required this.isArchive,
    required this.isImage,
    required this.isVideo,
    required this.isAudio,
    required this.size,
    required this.hasChildren,
    required this.childNames,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      isDir.hashCode ^
      isArchive.hashCode ^
      isImage.hashCode ^
      isVideo.hashCode ^
      isAudio.hashCode ^
      size.hashCode ^
      hasChildren.hashCode ^
      childNames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isDir == other.isDir &&
          isArchive == other.isArchive &&
          isImage == other.isImage &&
          isVideo == other.isVideo &&
          isAudio == other.isAudio &&
          size == other.size &&
          hasChildren == other.hasChildren &&
          childNames == other.childNames;
}

enum FileManagerEntryFilter { all, folders, archives, images, video, audio }

enum FileManagerInternalItemsMode { single, all }

class FileManagerSnapshot {
  final BigInt sessionId;
  final int maxTabs;
  final bool canCreateTab;
  final BigInt generation;
  final BigInt activeTabId;
  final String activePath;
  final bool canGoUp;
  final List<FileManagerBreadcrumb> breadcrumbs;
  final bool directoryColumnsEnabled;
  final List<FileManagerDirectoryColumn> directoryColumns;
  final List<FileManagerTab> tabs;
  final List<FileManagerTab> recentlyClosed;
  final List<FileManagerEntry> entries;
  final List<LocalRootLocation> roots;
  final bool penetrationEnabled;
  final bool showChildNames;
  final FileManagerInternalItemsMode internalItemsMode;
  final int maxDepth;
  final FileManagerViewMode viewMode;
  final bool showHiddenFiles;
  final String searchQuery;
  final FileManagerEntryFilter entryFilter;
  final FileManagerSortField sortField;
  final FileManagerSortOrder sortOrder;
  final bool directoriesFirst;

  const FileManagerSnapshot({
    required this.sessionId,
    required this.maxTabs,
    required this.canCreateTab,
    required this.generation,
    required this.activeTabId,
    required this.activePath,
    required this.canGoUp,
    required this.breadcrumbs,
    required this.directoryColumnsEnabled,
    required this.directoryColumns,
    required this.tabs,
    required this.recentlyClosed,
    required this.entries,
    required this.roots,
    required this.penetrationEnabled,
    required this.showChildNames,
    required this.internalItemsMode,
    required this.maxDepth,
    required this.viewMode,
    required this.showHiddenFiles,
    required this.searchQuery,
    required this.entryFilter,
    required this.sortField,
    required this.sortOrder,
    required this.directoriesFirst,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      maxTabs.hashCode ^
      canCreateTab.hashCode ^
      generation.hashCode ^
      activeTabId.hashCode ^
      activePath.hashCode ^
      canGoUp.hashCode ^
      breadcrumbs.hashCode ^
      directoryColumnsEnabled.hashCode ^
      directoryColumns.hashCode ^
      tabs.hashCode ^
      recentlyClosed.hashCode ^
      entries.hashCode ^
      roots.hashCode ^
      penetrationEnabled.hashCode ^
      showChildNames.hashCode ^
      internalItemsMode.hashCode ^
      maxDepth.hashCode ^
      viewMode.hashCode ^
      showHiddenFiles.hashCode ^
      searchQuery.hashCode ^
      entryFilter.hashCode ^
      sortField.hashCode ^
      sortOrder.hashCode ^
      directoriesFirst.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerSnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          maxTabs == other.maxTabs &&
          canCreateTab == other.canCreateTab &&
          generation == other.generation &&
          activeTabId == other.activeTabId &&
          activePath == other.activePath &&
          canGoUp == other.canGoUp &&
          breadcrumbs == other.breadcrumbs &&
          directoryColumnsEnabled == other.directoryColumnsEnabled &&
          directoryColumns == other.directoryColumns &&
          tabs == other.tabs &&
          recentlyClosed == other.recentlyClosed &&
          entries == other.entries &&
          roots == other.roots &&
          penetrationEnabled == other.penetrationEnabled &&
          showChildNames == other.showChildNames &&
          internalItemsMode == other.internalItemsMode &&
          maxDepth == other.maxDepth &&
          viewMode == other.viewMode &&
          showHiddenFiles == other.showHiddenFiles &&
          searchQuery == other.searchQuery &&
          entryFilter == other.entryFilter &&
          sortField == other.sortField &&
          sortOrder == other.sortOrder &&
          directoriesFirst == other.directoriesFirst;
}

enum FileManagerSortField { name, type, size }

enum FileManagerSortOrder { ascending, descending }

class FileManagerTab {
  final BigInt id;
  final String title;
  final String path;
  final bool canGoBack;
  final bool canGoForward;
  final bool pinned;
  final bool canClose;
  final bool canCloseOthers;
  final bool canCloseLeft;
  final bool canCloseRight;

  const FileManagerTab({
    required this.id,
    required this.title,
    required this.path,
    required this.canGoBack,
    required this.canGoForward,
    required this.pinned,
    required this.canClose,
    required this.canCloseOthers,
    required this.canCloseLeft,
    required this.canCloseRight,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      path.hashCode ^
      canGoBack.hashCode ^
      canGoForward.hashCode ^
      pinned.hashCode ^
      canClose.hashCode ^
      canCloseOthers.hashCode ^
      canCloseLeft.hashCode ^
      canCloseRight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerTab &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          path == other.path &&
          canGoBack == other.canGoBack &&
          canGoForward == other.canGoForward &&
          pinned == other.pinned &&
          canClose == other.canClose &&
          canCloseOthers == other.canCloseOthers &&
          canCloseLeft == other.canCloseLeft &&
          canCloseRight == other.canCloseRight;
}

enum FileManagerViewMode { list, grid }
