// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cancel_flag`, `execute_batch`, `finish_write`, `new`, `project_items`, `read_listing`, `refresh_listing`, `report_for`, `selection_mutations`, `snapshot_for`, `summary_for`, `with_ops`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FILE_OPS_CANCEL`, `FILE_OPS_SESSIONS`, `FileOpsSession`, `ListingSnapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `deref`, `deref`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`, `initialize`

Future<FileOpsSnapshot> fileOpsSnapshot({required BigInt id}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsSnapshot(id: id);

Future<FileOpsSnapshot> fileOpsSelectSingle({
  required BigInt id,
  required String path,
  required int index,
}) => RustLib.instance.api.crateApiFileOpsFileOpsSelectSingle(
  id: id,
  path: path,
  index: index,
);

Future<FileOpsSnapshot> fileOpsSelectToggle({
  required BigInt id,
  required String path,
  required int index,
}) => RustLib.instance.api.crateApiFileOpsFileOpsSelectToggle(
  id: id,
  path: path,
  index: index,
);

/// Shift 连选：从锚点连到 [end_index]。
Future<FileOpsSnapshot> fileOpsSelectChain({
  required BigInt id,
  required int endIndex,
  int? anchorIndex,
  required String endPath,
}) => RustLib.instance.api.crateApiFileOpsFileOpsSelectChain(
  id: id,
  endIndex: endIndex,
  anchorIndex: anchorIndex,
  endPath: endPath,
);

Future<FileOpsSnapshot> fileOpsSelectAll({required BigInt id}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsSelectAll(id: id);

Future<FileOpsSnapshot> fileOpsInvertSelection({required BigInt id}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsInvertSelection(id: id);

Future<FileOpsSnapshot> fileOpsClearSelection({required BigInt id}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsClearSelection(id: id);

/// 把当前选中项放进剪贴板。[cut] 为真时是剪切（粘贴时走 move）。
Future<FileOpsSnapshot> fileOpsCopyToClipboard({
  required BigInt id,
  required bool cut,
}) => RustLib.instance.api.crateApiFileOpsFileOpsCopyToClipboard(
  id: id,
  cut: cut,
);

Future<FileOpsSnapshot> fileOpsClearClipboard({required BigInt id}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsClearClipboard(id: id);

/// 粘贴。[destination] 为空 = 粘到当前目录；给了路径 = 粘到**那一项**里
/// （右键菜单的「粘贴到这一项」走这条，落点就是被右键的那个文件夹）。
Future<FileOpsReport> fileOpsPaste({required BigInt id, String? destination}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsPaste(
      id: id,
      destination: destination,
    );

Future<FileOpsReport> fileOpsTrashSelection({required BigInt id}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsTrashSelection(id: id);

Future<FileOpsReport> fileOpsDeleteSelection({required BigInt id}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsDeleteSelection(id: id);

/// 重命名一个条目。[new_name] 是新的**名字**，不是路径 —— 与上游一样要求同目录。
Future<FileOpsReport> fileOpsRenameEntry({
  required BigInt id,
  required String path,
  required String newName,
}) => RustLib.instance.api.crateApiFileOpsFileOpsRenameEntry(
  id: id,
  path: path,
  newName: newName,
);

/// 新建一个文件夹。[parent] 为空 = 建在当前目录；给了路径 = 建在**那一项**
/// （目录）里（右键菜单的「新建文件夹」走这条）。撞名时顺延成 `名字 (2)`
/// （见核心的 `unique_destination`）。
Future<FileOpsReport> fileOpsCreateDirectory({
  required BigInt id,
  required String name,
  String? parent,
}) => RustLib.instance.api.crateApiFileOpsFileOpsCreateDirectory(
  id: id,
  name: name,
  parent: parent,
);

/// 撤销最近一批。整份撤销日志一起回滚（对齐 neoview 的 `undo`：
/// 一次删除带来的那几条要一起回来，只回滚一半等于留下一个说不清的局面）。
Future<FileOpsReport> fileOpsUndo({required BigInt id}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsUndo(id: id);

/// 打断正在跑的那一批。**不会**中断正在落地的那一条 —— 文件操作没有安全的
/// 半途中断点；能让它停在条目边界，就已经避免了「后面几十项也照做」。
Future<bool> fileOpsCancel({required BigInt id}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsCancel(id: id);

/// 卡片关闭时回收。与 `file_manager_close` 成对调用。
Future<bool> fileOpsClose({required BigInt id}) =>
    RustLib.instance.api.crateApiFileOpsFileOpsClose(id: id);

/// 给判据用：这个平台能不能撤销回收站操作。UI 靠 [`FileOpsSnapshot`] 的同名字段，
/// 这里只是把一个纯查询也暴露出来，免得 Dart 侧为了问一句去开一个会话。
Future<bool> fileOpsTrashRestoreSupported() =>
    RustLib.instance.api.crateApiFileOpsFileOpsTrashRestoreSupported();

/// 剪贴板模式。`cut` 而不是 `move`：`move` 是 Rust 关键字，而且**剪贴板这一侧
/// 的语义本来就叫「剪切」** —— `move` 是它落到盘上的动作，不是用户做的选择。
enum FileOpsClipboardMode { copy, cut }

class FileOpsItemResult {
  final String path;
  final FileOpsItemStatus status;
  final String? errorCode;
  final String? error;

  const FileOpsItemResult({
    required this.path,
    required this.status,
    this.errorCode,
    this.error,
  });

  @override
  int get hashCode =>
      path.hashCode ^ status.hashCode ^ errorCode.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileOpsItemResult &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          status == other.status &&
          errorCode == other.errorCode &&
          error == other.error;
}

enum FileOpsItemStatus { succeeded, failed, cancelled }

class FileOpsReport {
  /// `copy` / `move` / `rename` / `delete` / `trash` / `create-directory`。
  final String kind;
  final int succeeded;
  final int failed;
  final int cancelled;

  /// 生成了回执、可以撤销的条数。
  final int undoable;

  /// 一句给提示条用的摘要，例如「已移到回收站 3 项，1 项失败」。
  final String summary;

  /// 逐条结果。UI 用它把失败项标回列表里的那一行。
  final List<FileOpsItemResult> items;

  /// 刷新过列表之后的新快照，省掉一次往返。
  final FileOpsSnapshot snapshot;

  const FileOpsReport({
    required this.kind,
    required this.succeeded,
    required this.failed,
    required this.cancelled,
    required this.undoable,
    required this.summary,
    required this.items,
    required this.snapshot,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      succeeded.hashCode ^
      failed.hashCode ^
      cancelled.hashCode ^
      undoable.hashCode ^
      summary.hashCode ^
      items.hashCode ^
      snapshot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileOpsReport &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          succeeded == other.succeeded &&
          failed == other.failed &&
          cancelled == other.cancelled &&
          undoable == other.undoable &&
          summary == other.summary &&
          items == other.items &&
          snapshot == other.snapshot;
}

class FileOpsSnapshot {
  final BigInt sessionId;

  /// 这份选中态对应的列表版本号。
  final BigInt generation;
  final int total;
  final int selectedCount;
  final bool allSelected;

  /// 当前选中的**路径**（已按下标 + 路径双轨解析，见核心 `selection` 模块）。
  final List<String> selectedPaths;

  /// 这些选中项里有没有目录（决定「粘贴进选中项」这类动作可不可用）。
  final bool selectionHasDirectory;

  /// 剪贴板非空且当前目录可粘贴。
  final bool canPaste;
  final FileOpsClipboardMode? clipboardMode;
  final int clipboardCount;
  final bool canUndo;
  final int undoCount;

  /// 这个平台上「移到回收站」能不能撤销。**macOS 为 false**。
  final bool trashRestoreSupported;

  const FileOpsSnapshot({
    required this.sessionId,
    required this.generation,
    required this.total,
    required this.selectedCount,
    required this.allSelected,
    required this.selectedPaths,
    required this.selectionHasDirectory,
    required this.canPaste,
    this.clipboardMode,
    required this.clipboardCount,
    required this.canUndo,
    required this.undoCount,
    required this.trashRestoreSupported,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      generation.hashCode ^
      total.hashCode ^
      selectedCount.hashCode ^
      allSelected.hashCode ^
      selectedPaths.hashCode ^
      selectionHasDirectory.hashCode ^
      canPaste.hashCode ^
      clipboardMode.hashCode ^
      clipboardCount.hashCode ^
      canUndo.hashCode ^
      undoCount.hashCode ^
      trashRestoreSupported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileOpsSnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          generation == other.generation &&
          total == other.total &&
          selectedCount == other.selectedCount &&
          allSelected == other.allSelected &&
          selectedPaths == other.selectedPaths &&
          selectionHasDirectory == other.selectionHasDirectory &&
          canPaste == other.canPaste &&
          clipboardMode == other.clipboardMode &&
          clipboardCount == other.clipboardCount &&
          canUndo == other.canUndo &&
          undoCount == other.undoCount &&
          trashRestoreSupported == other.trashRestoreSupported;
}
