// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'local.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_session_operation`, `attached_store`, `current_store`, `hydrate_view_states_from`, `load_search_history`, `map_entry`, `map_search_outcome`, `now_secs`, `pane_inputs`, `pane_sort_order`, `persist_dirty_view_states_into`, `project_pane`, `search_directory_of`, `seed_home_path`, `snapshot_for`, `store_for`, `with_pane`, `with_session`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FILE_MANAGER_PANES`, `FILE_MANAGER_SEARCHES`, `FILE_MANAGER_SESSIONS`, `FILE_MANAGER_STORE`, `FileManagerSearchGuard`, `NEXT_FILE_MANAGER_ID`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `deref`, `deref`, `deref`, `deref`, `deref`, `drop`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`, `initialize`, `initialize`, `initialize`, `initialize`

Future<BigInt> fileManagerCreate({
  String? initialPath,
  String? homePath,
  String? settingsDbPath,
  required bool rememberViewState,
}) => RustLib.instance.api.crateApiFileManagerFileManagerCreate(
  initialPath: initialPath,
  homePath: homePath,
  settingsDbPath: settingsDbPath,
  rememberViewState: rememberViewState,
);

Future<FileManagerSnapshot> fileManagerSnapshot({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerSnapshot(id: id);

Future<FileManagerSnapshot> fileManagerRefresh({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerRefresh(id: id);

Future<FileManagerSnapshot> fileManagerNavigate({
  required BigInt id,
  required String path,
}) => RustLib.instance.api.crateApiFileManagerFileManagerNavigate(
  id: id,
  path: path,
);

Future<FileManagerSnapshot> fileManagerNavigateText({
  required BigInt id,
  required String text,
}) => RustLib.instance.api.crateApiFileManagerFileManagerNavigateText(
  id: id,
  text: text,
);

Future<FileManagerSnapshot> fileManagerSetDirectoryColumns({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetDirectoryColumns(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerGoBack({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerGoBack(id: id);

Future<FileManagerSnapshot> fileManagerGoForward({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerGoForward(id: id);

Future<FileManagerSnapshot> fileManagerGoUp({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerGoUp(id: id);

/// 跳回用户指定的主页。主页就是普通目录，因此同样进入页签的后退栈。
Future<FileManagerSnapshot> fileManagerGoHome({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerGoHome(id: id);

/// 写入主页（`None` 清除）。核心只接受存在的目录，非法路径保持原值。
Future<FileManagerSnapshot> fileManagerSetHomePath({
  required BigInt id,
  String? path,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetHomePath(
  id: id,
  path: path,
);

Future<FileManagerSnapshot> fileManagerNewTab({
  required BigInt id,
  String? path,
}) => RustLib.instance.api.crateApiFileManagerFileManagerNewTab(
  id: id,
  path: path,
);

Future<FileManagerSnapshot> fileManagerActivateTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerActivateTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerCloseTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerDuplicateTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerDuplicateTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerToggleTabPinned({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerToggleTabPinned(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseOtherTabs({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerCloseOtherTabs(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseTabsLeft({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerCloseTabsLeft(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerCloseTabsRight({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerCloseTabsRight(
  id: id,
  tabId: tabId,
);

Future<FileManagerSnapshot> fileManagerReopenClosedTab({
  required BigInt id,
  required BigInt tabId,
}) => RustLib.instance.api.crateApiFileManagerFileManagerReopenClosedTab(
  id: id,
  tabId: tabId,
);

Future<FileManagerActionResult> fileManagerOpenEntry({
  required BigInt id,
  required String path,
  required bool forceEnter,
}) => RustLib.instance.api.crateApiFileManagerFileManagerOpenEntry(
  id: id,
  path: path,
  forceEnter: forceEnter,
);

/// Open an archive from a double-click without changing the browser location.
///
/// The core validates the path with mImageViewer's archive predicates, so every
/// UI gets the same ZIP/CBZ/RAR/7z/LZH handling and cannot accidentally route a
/// normal file through the archive gesture.
Future<FileManagerActionResult> fileManagerOpenArchive({
  required BigInt id,
  required String path,
}) => RustLib.instance.api.crateApiFileManagerFileManagerOpenArchive(
  id: id,
  path: path,
);

/// 按打开时的列表与目录栈查找上下本；不依赖仍在挂载的文件管理器。
Future<LocalBookNavigationTarget?> localBookAdjacent({
  required String path,
  String? navigationJson,
  required bool forward,
}) => RustLib.instance.api.crateApiFileManagerLocalBookAdjacent(
  path: path,
  navigationJson: navigationJson,
  forward: forward,
);

Future<FileManagerSnapshot> fileManagerSetPenetration({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetPenetration(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetShowChildNames({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetShowChildNames(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetInternalItemsMode({
  required BigInt id,
  required FileManagerInternalItemsMode mode,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetInternalItemsMode(
  id: id,
  mode: mode,
);

Future<FileManagerSnapshot> fileManagerSetMaxDepth({
  required BigInt id,
  required int depth,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetMaxDepth(
  id: id,
  depth: depth,
);

Future<FileManagerSnapshot> fileManagerSetViewMode({
  required BigInt id,
  required FileManagerViewMode mode,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetViewMode(
  id: id,
  mode: mode,
);

Future<FileManagerSnapshot> fileManagerSetShowHiddenFiles({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetShowHiddenFiles(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetSearchQuery({
  required BigInt id,
  required String query,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetSearchQuery(
  id: id,
  query: query,
);

Future<FileManagerSnapshot> fileManagerSetSearchInPath({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetSearchInPath(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetSearchOrMode({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetSearchOrMode(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetSearchIncludeSubfolders({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api
    .crateApiFileManagerFileManagerSetSearchIncludeSubfolders(
      id: id,
      enabled: enabled,
    );

Future<FileManagerSnapshot> fileManagerSetSearchMaxDepth({
  required BigInt id,
  required int depth,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetSearchMaxDepth(
  id: id,
  depth: depth,
);

/// 按当前生效的搜索条件跑一次递归搜索。
///
/// 遍历**不**在 `with_session` 里跑：那个闭包握着会话的写锁，一次整库扫描会把
/// 其它卡片动作全部堵住。所以先取一份请求值（根路径 + 设置快照），再在阻塞线程
/// 上离线遍历。代价是遍历期间用户改设置不生效 —— 那本来就该由下一次搜索回答。
Future<FileManagerSnapshot> fileManagerSearch({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerSearch(id: id);

/// 把当前搜索结果另存成一个页签（NeoView 的「保存搜索到页签」）。
Future<FileManagerSnapshot> fileManagerSaveSearchAsTab({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerSaveSearchAsTab(id: id);

/// 退出搜索结果视图，回到页签自己那一层目录（不清空搜索词）。
Future<FileManagerSnapshot> fileManagerClearSearch({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerClearSearch(id: id);

/// 请求中止本会话正在跑的搜索。没有搜索在跑时是空操作。
Future<bool> fileManagerCancelSearch({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerCancelSearch(id: id);

/// 记一次搜索到历史里，并回给最新的列表（省得 Dart 再问一次）。
///
/// 设置库没打开时返回空列表而**不是**报错：历史是辅助信息，一次 SQLite 不可用
/// 不该让搜索框冒红。真正的搜索早已独立完成。
Future<List<String>> fileManagerRecordSearchHistory({required String query}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerRecordSearchHistory(
      query: query,
    );

Future<List<String>> fileManagerSearchHistory({required int limit}) => RustLib
    .instance
    .api
    .crateApiFileManagerFileManagerSearchHistory(limit: limit);

Future<int> fileManagerClearSearchHistory() =>
    RustLib.instance.api.crateApiFileManagerFileManagerClearSearchHistory();

Future<FileManagerSnapshot> fileManagerSetEntryFilter({
  required BigInt id,
  required FileManagerEntryFilter filter,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetEntryFilter(
  id: id,
  filter: filter,
);

Future<FileManagerSnapshot> fileManagerSetSort({
  required BigInt id,
  required FileManagerSortField field,
  required FileManagerSortOrder order,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetSort(
  id: id,
  field: field,
  order: order,
);

/// 工具栏的「锁定当前目录排序／取消临时排序」。
Future<FileManagerSnapshot> fileManagerSetSortTemporary({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetSortTemporary(
  id: id,
  enabled: enabled,
);

/// 「记住每个目录的视图与排序」总开关（对应全局设置里那一项）。
///
/// 置为 false 之后本会话既不读也不写目录偏好；已经存下来的行**不删**，
/// 所以重新打开开关就能恢复，与 mImageViewer 的 `remember_favorite_view_state` 同口径。
Future<FileManagerSnapshot> fileManagerSetRememberViewState({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetRememberViewState(
  id: id,
  enabled: enabled,
);

Future<FileManagerSnapshot> fileManagerSetDirectoriesFirst({
  required BigInt id,
  required bool enabled,
}) => RustLib.instance.api.crateApiFileManagerFileManagerSetDirectoriesFirst(
  id: id,
  enabled: enabled,
);

bool fileManagerClose({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerClose(id: id);

Future<FileManagerTreeSnapshot> fileManagerTreeSnapshot({required BigInt id}) =>
    RustLib.instance.api.crateApiFileManagerFileManagerTreeSnapshot(id: id);

/// 展开/收起某一行。核心没有「按路径直接改展开态」的入口，于是把游标挪过去、
/// 再走键盘的左/右键 —— 与用户用方向键操作时是同一条路径，展开状态（`user_expanded`
/// / `user_collapsed`）的记账因此只有一套。
Future<FileManagerTreeSnapshot> fileManagerTreeToggle({
  required BigInt id,
  required String path,
}) => RustLib.instance.api.crateApiFileManagerFileManagerTreeToggle(
  id: id,
  path: path,
);

class FileManagerActionResult {
  final FileManagerSnapshot snapshot;

  /// 非空时表示 UI 应该把该路径交给 Reader；浏览器自身仍停留在原目录。
  final String? openedPath;

  /// 核心拥有的上下本游标；UI 只需随阅读目标透传。
  final String? bookNavigationJson;

  const FileManagerActionResult({
    required this.snapshot,
    this.openedPath,
    this.bookNavigationJson,
  });

  @override
  int get hashCode =>
      snapshot.hashCode ^ openedPath.hashCode ^ bookNavigationJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerActionResult &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          openedPath == other.openedPath &&
          bookNavigationJson == other.bookNavigationJson;
}

class FileManagerBreadcrumb {
  final String path;
  final String name;
  final bool isRoot;
  final bool isCurrent;

  const FileManagerBreadcrumb({
    required this.path,
    required this.name,
    required this.isRoot,
    required this.isCurrent,
  });

  @override
  int get hashCode =>
      path.hashCode ^ name.hashCode ^ isRoot.hashCode ^ isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerBreadcrumb &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isRoot == other.isRoot &&
          isCurrent == other.isCurrent;
}

class FileManagerChild {
  final String path;
  final String name;
  final bool isDir;
  final bool isArchive;
  final bool isImage;
  final bool isVideo;
  final bool isAudio;

  const FileManagerChild({
    required this.path,
    required this.name,
    required this.isDir,
    required this.isArchive,
    required this.isImage,
    required this.isVideo,
    required this.isAudio,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      isDir.hashCode ^
      isArchive.hashCode ^
      isImage.hashCode ^
      isVideo.hashCode ^
      isAudio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerChild &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isDir == other.isDir &&
          isArchive == other.isArchive &&
          isImage == other.isImage &&
          isVideo == other.isVideo &&
          isAudio == other.isAudio;
}

class FileManagerDirectoryChoice {
  final String path;
  final String name;
  final bool selected;

  const FileManagerDirectoryChoice({
    required this.path,
    required this.name,
    required this.selected,
  });

  @override
  int get hashCode => path.hashCode ^ name.hashCode ^ selected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerDirectoryChoice &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          selected == other.selected;
}

class FileManagerDirectoryColumn {
  final String path;
  final String name;
  final List<FileManagerDirectoryChoice> entries;
  final String? error;

  const FileManagerDirectoryColumn({
    required this.path,
    required this.name,
    required this.entries,
    this.error,
  });

  @override
  int get hashCode =>
      path.hashCode ^ name.hashCode ^ entries.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerDirectoryColumn &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          entries == other.entries &&
          error == other.error;
}

class FileManagerEntry {
  final String path;
  final String name;
  final bool isDir;
  final bool isArchive;
  final bool isImage;
  final bool isVideo;
  final bool isAudio;
  final BigInt size;
  final PlatformInt64 modifiedSecs;
  final bool hasChildren;

  /// NeoView 的「显示内部条目」投影。它不改变父目录列表，只为 UI 提供一小段
  /// 可点击的上下文提示。
  final List<FileManagerChild> childNames;

  /// 搜索结果页签里，这条命中在搜索根之下的目录（`/` 分隔）。普通浏览时为 `None`
  /// —— 那时父目录就是当前目录，写出来只是噪音。
  final String? searchDirectory;

  const FileManagerEntry({
    required this.path,
    required this.name,
    required this.isDir,
    required this.isArchive,
    required this.isImage,
    required this.isVideo,
    required this.isAudio,
    required this.size,
    required this.modifiedSecs,
    required this.hasChildren,
    required this.childNames,
    this.searchDirectory,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      isDir.hashCode ^
      isArchive.hashCode ^
      isImage.hashCode ^
      isVideo.hashCode ^
      isAudio.hashCode ^
      size.hashCode ^
      modifiedSecs.hashCode ^
      hasChildren.hashCode ^
      childNames.hashCode ^
      searchDirectory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          isDir == other.isDir &&
          isArchive == other.isArchive &&
          isImage == other.isImage &&
          isVideo == other.isVideo &&
          isAudio == other.isAudio &&
          size == other.size &&
          modifiedSecs == other.modifiedSecs &&
          hasChildren == other.hasChildren &&
          childNames == other.childNames &&
          searchDirectory == other.searchDirectory;
}

enum FileManagerEntryFilter { all, folders, archives, images, video, audio }

enum FileManagerInternalItemsMode { single, all }

class FileManagerSnapshot {
  final BigInt sessionId;
  final int maxTabs;
  final bool canCreateTab;
  final BigInt generation;
  final BigInt activeTabId;
  final String activePath;
  final bool canGoUp;
  final List<FileManagerBreadcrumb> breadcrumbs;
  final bool directoryColumnsEnabled;
  final List<FileManagerDirectoryColumn> directoryColumns;
  final List<FileManagerTab> tabs;
  final List<FileManagerTab> recentlyClosed;
  final List<FileManagerEntry> entries;
  final List<LocalRootLocation> roots;
  final bool penetrationEnabled;
  final bool showChildNames;
  final FileManagerInternalItemsMode internalItemsMode;
  final int maxDepth;
  final FileManagerViewMode viewMode;
  final bool showHiddenFiles;
  final String searchQuery;

  /// 名称之外是否连同「相对搜索根的路径」一起匹配。
  final bool searchInPath;

  /// 多个词元的结合方式（false = AND，true = OR）。
  final bool searchOrMode;

  /// 递归搜索是否连同子目录。关掉时 `search_max_depth` 不参与。
  final bool searchIncludeSubfolders;

  /// 递归层数上限（实际生效值再被核心的 `MAX_SEARCH_DEPTH` 夹一次）。
  final int searchMaxDepth;

  /// 当前页签是不是「搜索结果页签」：列表画的是上一次遍历的命中，而不是目录。
  final bool searchActive;

  /// 这批命中对应的查询（说明文案与页签标题用）。
  final String searchResultQuery;

  /// 检视过的条目数（含未命中）。区分「没有」与「还没扫到」。
  final int searchScanned;

  /// 命中总数，可能因上限截断而大于列表长度。
  final int searchMatched;
  final bool searchTruncated;
  final bool searchCancelled;

  /// 「把当前搜索存成页签」是否可用（需要有结果）。
  final bool canSaveSearchTab;
  final FileManagerEntryFilter entryFilter;
  final FileManagerSortField sortField;
  final FileManagerSortOrder sortOrder;
  final bool directoriesFirst;

  /// 用户指定的主页；`None` 时工具栏的主页键应禁用。
  final String? homePath;
  final bool isHome;
  final bool canSetHome;

  /// 「临时排序」：排序变更不写回当前目录的视图状态。
  final bool sortTemporary;

  /// 目录级排序偏好是否可用（`remember_view_state`）。
  final bool canSortPreference;

  /// 「记住每个目录的视图与排序」总开关的当前值。关闭时本会话不读不写目录偏好。
  final bool rememberViewState;

  const FileManagerSnapshot({
    required this.sessionId,
    required this.maxTabs,
    required this.canCreateTab,
    required this.generation,
    required this.activeTabId,
    required this.activePath,
    required this.canGoUp,
    required this.breadcrumbs,
    required this.directoryColumnsEnabled,
    required this.directoryColumns,
    required this.tabs,
    required this.recentlyClosed,
    required this.entries,
    required this.roots,
    required this.penetrationEnabled,
    required this.showChildNames,
    required this.internalItemsMode,
    required this.maxDepth,
    required this.viewMode,
    required this.showHiddenFiles,
    required this.searchQuery,
    required this.searchInPath,
    required this.searchOrMode,
    required this.searchIncludeSubfolders,
    required this.searchMaxDepth,
    required this.searchActive,
    required this.searchResultQuery,
    required this.searchScanned,
    required this.searchMatched,
    required this.searchTruncated,
    required this.searchCancelled,
    required this.canSaveSearchTab,
    required this.entryFilter,
    required this.sortField,
    required this.sortOrder,
    required this.directoriesFirst,
    this.homePath,
    required this.isHome,
    required this.canSetHome,
    required this.sortTemporary,
    required this.canSortPreference,
    required this.rememberViewState,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      maxTabs.hashCode ^
      canCreateTab.hashCode ^
      generation.hashCode ^
      activeTabId.hashCode ^
      activePath.hashCode ^
      canGoUp.hashCode ^
      breadcrumbs.hashCode ^
      directoryColumnsEnabled.hashCode ^
      directoryColumns.hashCode ^
      tabs.hashCode ^
      recentlyClosed.hashCode ^
      entries.hashCode ^
      roots.hashCode ^
      penetrationEnabled.hashCode ^
      showChildNames.hashCode ^
      internalItemsMode.hashCode ^
      maxDepth.hashCode ^
      viewMode.hashCode ^
      showHiddenFiles.hashCode ^
      searchQuery.hashCode ^
      searchInPath.hashCode ^
      searchOrMode.hashCode ^
      searchIncludeSubfolders.hashCode ^
      searchMaxDepth.hashCode ^
      searchActive.hashCode ^
      searchResultQuery.hashCode ^
      searchScanned.hashCode ^
      searchMatched.hashCode ^
      searchTruncated.hashCode ^
      searchCancelled.hashCode ^
      canSaveSearchTab.hashCode ^
      entryFilter.hashCode ^
      sortField.hashCode ^
      sortOrder.hashCode ^
      directoriesFirst.hashCode ^
      homePath.hashCode ^
      isHome.hashCode ^
      canSetHome.hashCode ^
      sortTemporary.hashCode ^
      canSortPreference.hashCode ^
      rememberViewState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerSnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          maxTabs == other.maxTabs &&
          canCreateTab == other.canCreateTab &&
          generation == other.generation &&
          activeTabId == other.activeTabId &&
          activePath == other.activePath &&
          canGoUp == other.canGoUp &&
          breadcrumbs == other.breadcrumbs &&
          directoryColumnsEnabled == other.directoryColumnsEnabled &&
          directoryColumns == other.directoryColumns &&
          tabs == other.tabs &&
          recentlyClosed == other.recentlyClosed &&
          entries == other.entries &&
          roots == other.roots &&
          penetrationEnabled == other.penetrationEnabled &&
          showChildNames == other.showChildNames &&
          internalItemsMode == other.internalItemsMode &&
          maxDepth == other.maxDepth &&
          viewMode == other.viewMode &&
          showHiddenFiles == other.showHiddenFiles &&
          searchQuery == other.searchQuery &&
          searchInPath == other.searchInPath &&
          searchOrMode == other.searchOrMode &&
          searchIncludeSubfolders == other.searchIncludeSubfolders &&
          searchMaxDepth == other.searchMaxDepth &&
          searchActive == other.searchActive &&
          searchResultQuery == other.searchResultQuery &&
          searchScanned == other.searchScanned &&
          searchMatched == other.searchMatched &&
          searchTruncated == other.searchTruncated &&
          searchCancelled == other.searchCancelled &&
          canSaveSearchTab == other.canSaveSearchTab &&
          entryFilter == other.entryFilter &&
          sortField == other.sortField &&
          sortOrder == other.sortOrder &&
          directoriesFirst == other.directoriesFirst &&
          homePath == other.homePath &&
          isHome == other.isHome &&
          canSetHome == other.canSetHome &&
          sortTemporary == other.sortTemporary &&
          canSortPreference == other.canSortPreference &&
          rememberViewState == other.rememberViewState;
}

enum FileManagerSortField { name, type, size, date, random }

enum FileManagerSortOrder { ascending, descending }

class FileManagerTab {
  final BigInt id;
  final String title;
  final String path;
  final bool canGoBack;
  final bool canGoForward;
  final bool pinned;
  final bool canClose;
  final bool canCloseOthers;
  final bool canCloseLeft;
  final bool canCloseRight;

  const FileManagerTab({
    required this.id,
    required this.title,
    required this.path,
    required this.canGoBack,
    required this.canGoForward,
    required this.pinned,
    required this.canClose,
    required this.canCloseOthers,
    required this.canCloseLeft,
    required this.canCloseRight,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      path.hashCode ^
      canGoBack.hashCode ^
      canGoForward.hashCode ^
      pinned.hashCode ^
      canClose.hashCode ^
      canCloseOthers.hashCode ^
      canCloseLeft.hashCode ^
      canCloseRight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerTab &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          path == other.path &&
          canGoBack == other.canGoBack &&
          canGoForward == other.canGoForward &&
          pinned == other.pinned &&
          canClose == other.canClose &&
          canCloseOthers == other.canCloseOthers &&
          canCloseLeft == other.canCloseLeft &&
          canCloseRight == other.canCloseRight;
}

/// 文件树的一行：核心 `FolderPaneRow` 的字符串投影。
class FileManagerTreeRow {
  final String path;
  final String name;
  final int depth;
  final bool expanded;

  /// 子目录正在后台枚举：这一行的箭头该转圈。
  final bool loading;

  /// 「有子目录，或者还没查过」。确认是空目录时 UI 才收起箭头。
  final bool mayHaveChildren;
  final bool isActive;
  final String? error;

  const FileManagerTreeRow({
    required this.path,
    required this.name,
    required this.depth,
    required this.expanded,
    required this.loading,
    required this.mayHaveChildren,
    required this.isActive,
    this.error,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      depth.hashCode ^
      expanded.hashCode ^
      loading.hashCode ^
      mayHaveChildren.hashCode ^
      isActive.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerTreeRow &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          depth == other.depth &&
          expanded == other.expanded &&
          loading == other.loading &&
          mayHaveChildren == other.mayHaveChildren &&
          isActive == other.isActive &&
          error == other.error;
}

class FileManagerTreeSnapshot {
  final List<FileManagerTreeRow> rows;

  /// 仍有目录在枚举中。UI 据此决定要不要隔一会儿再问一次。
  final bool hasPending;

  const FileManagerTreeSnapshot({required this.rows, required this.hasPending});

  @override
  int get hashCode => rows.hashCode ^ hasPending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileManagerTreeSnapshot &&
          runtimeType == other.runtimeType &&
          rows == other.rows &&
          hasPending == other.hasPending;
}

enum FileManagerViewMode {
  compact,
  coverList,
  mosaicList,
  details,
  coverGrid,
  mosaicGrid,
}

class LocalBookNavigationTarget {
  final String path;
  final String navigationJson;

  const LocalBookNavigationTarget({
    required this.path,
    required this.navigationJson,
  });

  @override
  int get hashCode => path.hashCode ^ navigationJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalBookNavigationTarget &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          navigationJson == other.navigationJson;
}
