// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 从 mImageViewer SQLite 目录数据库 (`CatalogDb`) 获取或按需生成单页缩略图。
///
/// 1. 优先查 SQLite (`{cache_dir}/{xx}/{sha256}.db` 的 `thumbnails` 表)；
/// 2. 命中返回 WebP 字节流；
/// 3. 未命中则后台从归档/文件夹读取、缩放、压缩为 WebP 存入 SQLite 并返回。
Future<Uint8List?> getLocalThumbnail({
  required String cacheDir,
  required String bookPath,
  required String entryName,
  required int pageIndex,
  int? maxLongSide,
}) => RustLib.instance.api.crateApiLocalThumbnailGetLocalThumbnail(
  cacheDir: cacheDir,
  bookPath: bookPath,
  entryName: entryName,
  pageIndex: pageIndex,
  maxLongSide: maxLongSide,
);

/// 从 SQLite 目录数据库直接读取整本漫画所有已缓存页面的真实宽高 (免解压大图)。
Future<Map<String, (int, int)>> getCachedBookPageDimensions({
  required String cacheDir,
  required String bookPath,
}) => RustLib.instance.api.crateApiLocalThumbnailGetCachedBookPageDimensions(
  cacheDir: cacheDir,
  bookPath: bookPath,
);

/// 获取整本书已缓存页面的推荐自动缩略图比例标签（如 "16:9", "1:1", "2:3" 等）。
Future<String?> getCachedBookAutoAspect({
  required String cacheDir,
  required String bookPath,
}) => RustLib.instance.api.crateApiLocalThumbnailGetCachedBookAutoAspect(
  cacheDir: cacheDir,
  bookPath: bookPath,
);

/// 获取或生成文件管理器条目 (文件夹、单张图片或漫画归档) 的缩略图。
///
/// 遵循 mImageViewer SQLite CatalogDb 与代表图推选逻辑。
Future<Uint8List?> getFileManagerEntryThumbnail({
  required String cacheDir,
  required String entryPath,
  required bool isDir,
  required bool isArchive,
  required bool isImage,
  String? sortOrder,
  int? maxDepth,
  int? maxLongSide,
}) => RustLib.instance.api.crateApiLocalThumbnailGetFileManagerEntryThumbnail(
  cacheDir: cacheDir,
  entryPath: entryPath,
  isDir: isDir,
  isArchive: isArchive,
  isImage: isImage,
  sortOrder: sortOrder,
  maxDepth: maxDepth,
  maxLongSide: maxLongSide,
);
