// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `classify_open_error`, `decode_failed`, `decode_page_impl`, `open_local_source_impl`, `session`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FS_PAGE_LOAD`, `NEXT_LOAD_SEQ`, `NEXT_SESSION_ID`, `SESSIONS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `deref`, `deref`, `deref`, `deref`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `initialize`, `initialize`, `initialize`, `initialize`

Future<LocalSourceOpenResult> openLocalSource({required String path}) =>
    RustLib.instance.api.crateApiLocalOpenLocalSource(path: path);

Future<List<LocalPageInfo>> localSourcePages({required BigInt id}) =>
    RustLib.instance.api.crateApiLocalLocalSourcePages(id: id);

/// 取一页的**编码字节**。每调用一次都会重新打开来源（不常驻句柄，判据 D）。
Future<Uint8List> localPageBytes({required BigInt id, required int index}) =>
    RustLib.instance.api.crateApiLocalLocalPageBytes(id: id, index: index);

/// 取一页的**解码后像素**。
///
/// 和 [`local_page_bytes`] 的分工必须说清，否则很容易用错：
/// - `local_page_bytes` 给的是**编码字节**，Dart 侧自己解 —— 只对 Dart 引擎认识的格式有效。
///   Windows 引擎没有 AV1 解码器，所以 avif 走那条路只会得到
///   `Could not decompress image.`（实测见 `rossi_local_core::page_order`）。
/// - 这一条走 **Rust 侧解码器**，是 avif 目前唯一能出图的路。
///
/// # `target_width`：这个参数决定这条路径能不能用
///
/// `None` = 原尺寸。**对 44.8 MPix 的页，原尺寸是不可接受的**：
/// Rust 侧解出来只要约 267 ms（其中 dav1d 249 ms），但 170 MB 的位图
/// 过桥 + 交给 `ui.decodeImageFromPixels` 要多花约 1260 ms —— 实测 App 里
/// 同一页量到 1526 ms，**其中解码只占 17%**。
///
/// 给了 `target_width` 之后，位图按宽度降采样（不放大），后面那 1260 ms
/// 随位图大小等比下降：缩到 768 px 时位图 3.4 MB，Rust 侧总成本约 305 ms。
/// 完整档位实测见 `rossi_local_core::decode::decode_rgba_scaled`。
///
/// # 这是过渡形态，不是终点
///
/// Phase 1 的目标是「Rust 解码 → GPU texture 上屏」，那一步**不过桥**，
/// 因而也不需要靠降采样来省拷贝。判据 C 的 p95 ≤ 16.7 ms 不在当前形态下成立，
/// 别拿它的数字当结论。
Future<LocalPageDecodeResult> localPagePixels({
  required BigInt id,
  required int index,
  int? targetWidth,
  required LocalPageLoadPriority priority,
  required LocalPageLoadContract contract,
}) => RustLib.instance.api.crateApiLocalLocalPagePixels(
  id: id,
  index: index,
  targetWidth: targetWidth,
  priority: priority,
  contract: contract,
);

/// 现在该不该发预取。
///
/// 上游语义在这里一一对应（分页阅读 vs 连续阅读，判据同构）：
///
/// | 上游（连续阅读） | 这里（分页阅读） |
/// |---|---|
/// | `last_prefetch_scroll_at` | 上一次翻页/跳页的时刻，用「距现在多少毫秒」传 |
/// | `visible_state_pending` | 当前页是否还没出图（0 = 已出图） |
///
/// `Instant` 不能跨桥，所以传毫秒差；还原成 `Instant` 是这一层唯一的翻译动作。
///
/// 三种放行：还没翻过页 / 翻完 100 ms 且当前页已出图 / 距上次翻页满 3 秒
/// （兜底：防止「当前页永远加载不出来」把预取永久冻住）。
Future<LocalPrefetchDecision> localPrefetchDecision({
  BigInt? msSinceLastTurn,
  required int visiblePending,
}) => RustLib.instance.api.crateApiLocalLocalPrefetchDecision(
  msSinceLastTurn: msSinceLastTurn,
  visiblePending: visiblePending,
);

/// 预取目标（页序号）。顺序是 `+1, -1, +2, -2, …`，同距离 **forward 先**。
///
/// 为什么 forward 先：下一个要看的页大概率是下一页；而 backward 那页用户刚看过，
/// 它的解码结果很可能还在（或还在用），先解它等于把许可花在更没用的地方。
///
/// 边界由上游函数处理：`pos` 在头/尾时只有一侧有值，越界的位置直接跳过。
Future<Uint32List> localPrefetchTargets({
  required int pos,
  required int n,
  required int forward,
  required int back,
}) => RustLib.instance.api.crateApiLocalLocalPrefetchTargets(
  pos: pos,
  n: n,
  forward: forward,
  back: back,
);

Future<LocalPageLoadStats> localPageLoadStats() =>
    RustLib.instance.api.crateApiLocalLocalPageLoadStats();

/// 关闭会话并释放。返回 `false` 表示 id 不存在（重复关闭、或已被回收）。
bool localClose({required BigInt id}) =>
    RustLib.instance.api.crateApiLocalLocalClose(id: id);

/// 当前打开的会话数。
///
/// 这是判据 D 的**探针**：连读三本之后，这个数必须回落到基线附近，
/// 不允许单调上升。GPU/handle 侧泄漏不体现在 RSS 里，只能靠这种计数观测。
int localOpenSessionCount() =>
    RustLib.instance.api.crateApiLocalLocalOpenSessionCount();

/// 关闭全部会话。用于「换书」「退出阅读器」这类整批释放的场景。
int localCloseAll() => RustLib.instance.api.crateApiLocalLocalCloseAll();

class LocalDecodeFailure {
  final LocalDecodeFailureKind kind;

  /// 可直接展示的说明（已本地化）。
  final String message;

  const LocalDecodeFailure({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalDecodeFailure &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// 解码失败的**类别**。用枚举而不是字符串，理由与 `LocalRejection` 相同：
/// 「这一页的格式核心没解码器」和「字节坏了」给用户的下一步动作完全不同。
enum LocalDecodeFailureKind {
  /// 核心没有这个格式的解码器（`jxl` / `heic` / `heif`），要交外壳 —— 而外壳解得动
  /// 与否取决于平台（Windows 引擎实测解不动，见 `rossi_local_core::page_order`）。
  shellOnlyFormat,

  /// 核心有解码器但没解出来：字节损坏、内容与格式不符等。
  decodeFailed,

  /// **没轮到就作废了**：请求还在排队时被更新的 `LatestSeek` 取代，或调用方放弃。
  ///
  /// 与上两者分开，是因为它既不是格式问题也不是数据问题 —— **这一页完全可能解得出**，
  /// 只是没人要了。UI 不该把它显示成错误，更不该据此判定「这本解不了」。
  cancelled,
}

/// `local_page_pixels` 的返回值：要么 `pixels`，要么 `failure`。
class LocalPageDecodeResult {
  final LocalPagePixels? pixels;
  final LocalDecodeFailure? failure;

  const LocalPageDecodeResult({this.pixels, this.failure});

  @override
  int get hashCode => pixels.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalPageDecodeResult &&
          runtimeType == other.runtimeType &&
          pixels == other.pixels &&
          failure == other.failure;
}

class LocalPageInfo {
  final int index;

  /// 展示名（页序已由 Rust 侧自然序决定，Dart 侧不要再排一次）。
  final String name;

  /// 编码字节数。文件夹来源为文件长度。
  final BigInt size;

  const LocalPageInfo({
    required this.index,
    required this.name,
    required this.size,
  });

  @override
  int get hashCode => index.hashCode ^ name.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalPageInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name &&
          size == other.size;
}

/// 这次页加载的**准入契约**。语义来自 mImageViewer 的 `FsPageLoadContract`。
///
/// 区别只在「它会不会作废别的请求」：
/// - `Sequential`：顺序翻页。**永不**作废已受理的目标 —— 连翻三页就是三页都要，
///   中间那页用户真的看过。
/// - `LatestSeek`：直接跳页。用户已经改主意了，同一会话里还在排队的旧请求
///   全部作废（它们读完也没人看），从而把许可让给新的目标。
enum LocalPageLoadContract { sequential, latestSeek }

/// 这次页加载的**优先级**。语义来自 mImageViewer 的 `FsPageLoadPriority`。
///
/// 为什么要有它：用户正在等的那一页（`High`）必须能插队到预取（`Normal`）前面，
/// 否则「预取把全部许可占满、用户翻页排在后面」就是必然。
/// 调度器为此留了 2 张许可只给 `High`。
enum LocalPageLoadPriority {
  /// 预取、预热之类：可以等。
  normal,

  /// 用户此刻在等这一页。
  high,
}

/// 调度器此刻的快照 —— 「在跑几个解码」。
///
/// 这是 `FS_PAGE_LOAD` 的**可观测面**。没有它，判据 D（连读内存不增长）与
/// 「预取有没有在抢当前页的许可」只能靠感觉判断。
class LocalPageLoadStats {
  final int waiting;
  final int running;
  final int cancelling;
  final int runningNormal;
  final int totalLimit;
  final int highReserved;

  const LocalPageLoadStats({
    required this.waiting,
    required this.running,
    required this.cancelling,
    required this.runningNormal,
    required this.totalLimit,
    required this.highReserved,
  });

  @override
  int get hashCode =>
      waiting.hashCode ^
      running.hashCode ^
      cancelling.hashCode ^
      runningNormal.hashCode ^
      totalLimit.hashCode ^
      highReserved.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalPageLoadStats &&
          runtimeType == other.runtimeType &&
          waiting == other.waiting &&
          running == other.running &&
          cancelling == other.cancelling &&
          runningNormal == other.runningNormal &&
          totalLimit == other.totalLimit &&
          highReserved == other.highReserved;
}

/// 一页解码后的像素（RGBA8，未预乘，行主序）。
class LocalPagePixels {
  final int width;
  final int height;

  /// 解码器输出的原始尺寸（降采样之前）。与 `width`/`height` 分开，
  /// 是为了让「请求的宽度到底生效了没有」在 UI 上一眼可见。
  final int sourceWidth;
  final int sourceHeight;

  /// `width * height * 4` 字节。
  final Uint8List rgba;

  const LocalPagePixels({
    required this.width,
    required this.height,
    required this.sourceWidth,
    required this.sourceHeight,
    required this.rgba,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      sourceWidth.hashCode ^
      sourceHeight.hashCode ^
      rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalPagePixels &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          sourceWidth == other.sourceWidth &&
          sourceHeight == other.sourceHeight &&
          rgba == other.rgba;
}

/// 预取准入判决的结果。
///
/// 带**理由**而不是一个 bool —— 上游的理由枚举（`AllowReason` / `BlockReason`）
/// 就是为了让人看到「现在为什么不预取」。只返回 bool 的话，调试页只能显示
/// 「没预取」，而「因为当前页还在加载」和「因为你刚翻页 43 ms」是完全不同的两件事，
/// 对应的下一步动作也不同。
class LocalPrefetchDecision {
  final bool allowed;

  /// 机器可读的理由标签。
  final String reason;

  /// 可直接展示的说明（中文）。
  final String message;

  const LocalPrefetchDecision({
    required this.allowed,
    required this.reason,
    required this.message,
  });

  @override
  int get hashCode => allowed.hashCode ^ reason.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalPrefetchDecision &&
          runtimeType == other.runtimeType &&
          allowed == other.allowed &&
          reason == other.reason &&
          message == other.message;
}

class LocalRejection {
  final LocalRejectionKind kind;

  /// 可直接展示给用户的说明（已本地化）。
  final String message;

  const LocalRejection({required this.kind, required this.message});

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalRejection &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// 被**主动拒绝**的原因类别。UI 按类别给不同提示与下一步动作。
enum LocalRejectionKind {
  /// 扩展名不在 v0.1 范围内（7z / PDF / 视频……）。
  unknownFormat,

  /// 固实 RAR：读第 N 页要解压前 N-1 页。
  rarSolid,

  /// 归档里含嵌套归档（v0.1 不展开）。
  rarNestedArchive,

  /// 加密 RAR（v0.1 不提供密码输入）。
  rarEncrypted,

  /// 路径不存在或不可读。
  notFound,

  /// 其他 IO / 解析失败（含归档损坏）。
  io,
}

class LocalSourceInfo {
  /// 会话 id，后续所有调用都用它。
  final BigInt id;
  final String path;
  final LocalSourceKind kind;
  final int pageCount;
  final BigInt totalBytes;

  const LocalSourceInfo({
    required this.id,
    required this.path,
    required this.kind,
    required this.pageCount,
    required this.totalBytes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      kind.hashCode ^
      pageCount.hashCode ^
      totalBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalSourceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          kind == other.kind &&
          pageCount == other.pageCount &&
          totalBytes == other.totalBytes;
}

/// 来源类型。与 `rossi_local_core::SourceKind` 一一对应（单独声明是为了不受
/// 依赖里的类型改动直接影响 Dart 侧的枚举名）。
enum LocalSourceKind { folder, zip, rar }

/// `open_local_source` 的返回值：要么拿到 `source`，要么拿到 `rejection`，不会两者都有。
class LocalSourceOpenResult {
  final LocalSourceInfo? source;
  final LocalRejection? rejection;

  const LocalSourceOpenResult({this.source, this.rejection});

  @override
  int get hashCode => source.hashCode ^ rejection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalSourceOpenResult &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          rejection == other.rejection;
}
