// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 从 mImageViewer SQLite 目录数据库 (`CatalogDb`) 获取或按需生成单页缩略图。
///
/// 1. 优先查 SQLite (`{cache_dir}/{xx}/{sha256}.db` 的 `thumbnails` 表)；
/// 2. 命中返回 WebP 字节流；
/// 3. 未命中则后台从归档/文件夹读取、缩放、压缩为 WebP 存入 SQLite 并返回。
Future<Uint8List?> getLocalThumbnail({
  required String cacheDir,
  required String bookPath,
  required String entryName,
  required int pageIndex,
  int? maxLongSide,
}) => RustLib.instance.api.crateApiLocalThumbnailGetLocalThumbnail(
  cacheDir: cacheDir,
  bookPath: bookPath,
  entryName: entryName,
  pageIndex: pageIndex,
  maxLongSide: maxLongSide,
);

/// 从 SQLite 目录数据库直接读取整本漫画所有已缓存页面的真实宽高 (免解压大图)。
Future<Map<String, (int, int)>> getCachedBookPageDimensions({
  required String cacheDir,
  required String bookPath,
}) => RustLib.instance.api.crateApiLocalThumbnailGetCachedBookPageDimensions(
  cacheDir: cacheDir,
  bookPath: bookPath,
);
