// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_ort`, `model_kind_file`

/// Run one mImage ONNX model and write a PNG. `model_path` must be a real
/// ONNX file; Git-LFS pointer files are rejected before inference.
Future<String> mimageOnnxUpscale({
  required String inputPath,
  required String outputPath,
  required String modelPath,
  required String modelId,
  required int tileSize,
}) => RustLib.instance.api.crateApiMimageOnnxMimageOnnxUpscale(
  inputPath: inputPath,
  outputPath: outputPath,
  modelPath: modelPath,
  modelId: modelId,
  tileSize: tileSize,
);
