// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `crop_with_pad`

/// 把「请求的 EP」翻译成「本机三段各自会用哪条」。纯函数：不读模型、不建会话。
///
/// 与 [`ocr_analyze_page`] 回报实际值用的是**同一把尺子**（`ocr_core::stage_ep_plan`），
/// 所以设置页说「将用 directml」与冒烟页说「实际用了 directml」不会各说各话。
OcrStageEpPlan ocrStageEpPlan({required String ep}) =>
    RustLib.instance.api.crateApiOcrOcrStageEpPlan(ep: ep);

/// 检测 → 识别 → 聚块（→ 可选擦字）。**不做翻译**，也不画字。
///
/// `ep` 取 `auto` / `cpu` / `coreml` / `directml`。**默认 `auto` = 按「平台 + 哪一段模型」选**
/// （Windows 上识别与擦字走 DirectML、检测走 CPU；其余平台走 CPU —— 数字见
/// `docs/REFERENCE_RESEARCH.md` §8.6.3）。显式选了不支持的不静默退回 CPU
/// （ADR-0018 §决定 3.1 的实测结论）。
Future<OcrPageResult> ocrAnalyzePage({
  required String imagePath,
  required OcrModelPaths models,
  required String ep,
  String? inpaintModel,
  String? erasedOutput,
  int? maxNewTokens,
}) => RustLib.instance.api.crateApiOcrOcrAnalyzePage(
  imagePath: imagePath,
  models: models,
  ep: ep,
  inpaintModel: inpaintModel,
  erasedOutput: erasedOutput,
  maxNewTokens: maxNewTokens,
);

/// 一个文本块。`quad` 是 8 个数（左上 / 右上 / 右下 / 左下，原图像素坐标）。
class OcrBlock {
  final Float32List quad;

  /// 按**列优先读序**拼好的原文（右→左、列内上→下）。
  final String text;

  /// 组成该块的检测框数量，用来判断这一块是否由多列拼成。
  final int boxes;

  /// 识别是否因达到上限被截断 —— 截断的文本应在上层标为可疑。
  final bool truncated;

  const OcrBlock({
    required this.quad,
    required this.text,
    required this.boxes,
    required this.truncated,
  });

  @override
  int get hashCode =>
      quad.hashCode ^ text.hashCode ^ boxes.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrBlock &&
          runtimeType == other.runtimeType &&
          quad == other.quad &&
          text == other.text &&
          boxes == other.boxes &&
          truncated == other.truncated;
}

/// 四个模型文件的路径。检测件与识别件分别来自各自的模型仓库，见 `REFERENCE_RESEARCH.md` §8.6.1。
class OcrModelPaths {
  final String det;
  final String encoder;
  final String decoder;
  final String vocab;

  const OcrModelPaths({
    required this.det,
    required this.encoder,
    required this.decoder,
    required this.vocab,
  });

  @override
  int get hashCode =>
      det.hashCode ^ encoder.hashCode ^ decoder.hashCode ^ vocab.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrModelPaths &&
          runtimeType == other.runtimeType &&
          det == other.det &&
          encoder == other.encoder &&
          decoder == other.decoder &&
          vocab == other.vocab;
}

/// 一页的分析结果。耗时字段的单位是毫秒。
class OcrPageResult {
  final List<OcrBlock> blocks;
  final int pageWidth;
  final int pageHeight;
  final BigInt detectMs;
  final BigInt recognizeMs;
  final BigInt inpaintMs;

  /// 擦干净的底图（仅在给了 `erased_output` 时写出）。译文要画在这张图上。
  final String? erasedPath;

  /// 这三段各自动用了哪条 EP。从各组件身上读回来（它们存的是 resolve 之后的值）。
  final OcrStageEps stageEps;

  const OcrPageResult({
    required this.blocks,
    required this.pageWidth,
    required this.pageHeight,
    required this.detectMs,
    required this.recognizeMs,
    required this.inpaintMs,
    this.erasedPath,
    required this.stageEps,
  });

  @override
  int get hashCode =>
      blocks.hashCode ^
      pageWidth.hashCode ^
      pageHeight.hashCode ^
      detectMs.hashCode ^
      recognizeMs.hashCode ^
      inpaintMs.hashCode ^
      erasedPath.hashCode ^
      stageEps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrPageResult &&
          runtimeType == other.runtimeType &&
          blocks == other.blocks &&
          pageWidth == other.pageWidth &&
          pageHeight == other.pageHeight &&
          detectMs == other.detectMs &&
          recognizeMs == other.recognizeMs &&
          inpaintMs == other.inpaintMs &&
          erasedPath == other.erasedPath &&
          stageEps == other.stageEps;
}

/// 设置页要显示的「本机三段落点」。每段 `None` = 本平台构建里没注册这条 EP，
/// 真跑会在建会话时报错（不静默退回 CPU）。
class OcrStageEpPlan {
  final String? detect;
  final String? recognize;
  final String? inpaint;

  const OcrStageEpPlan({this.detect, this.recognize, this.inpaint});

  @override
  int get hashCode => detect.hashCode ^ recognize.hashCode ^ inpaint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrStageEpPlan &&
          runtimeType == other.runtimeType &&
          detect == other.detect &&
          recognize == other.recognize &&
          inpaint == other.inpaint;
}

/// 三段各自**实际生效**的 EP（Rust 侧 `resolve` 之后的值，不是请求值）。
///
/// 为什么要它：`ep = auto` 时三段本来就该各走各的（Windows 上检测 CPU、
/// 识别与擦字 DirectML），只回报请求值等于什么都没说；而「选了 GPU 就不许偷偷用 CPU」
/// 这条纪律要成立，界面必须能核对**跑起来的那条**。
class OcrStageEps {
  final String detect;
  final String recognize;

  /// 没跑擦字（掩膜为空、或没给擦字模型）时是 `None` —— 界面显示「未跑」，
  /// 别让它看着像「跑了但用了 cpu」。
  final String? inpaint;

  const OcrStageEps({
    required this.detect,
    required this.recognize,
    this.inpaint,
  });

  @override
  int get hashCode => detect.hashCode ^ recognize.hashCode ^ inpaint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrStageEps &&
          runtimeType == other.runtimeType &&
          detect == other.detect &&
          recognize == other.recognize &&
          inpaint == other.inpaint;
}
