// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `crop_with_pad`

/// 检测 → 识别 → 聚块（→ 可选擦字）。**不做翻译**，也不画字。
///
/// `ep` 取 `cpu` / `coreml` / `directml`：EP 按模型指定，且选了不支持的不静默退回 CPU
/// （ADR-0018 §决定 3.1 的实测结论）。
Future<OcrPageResult> ocrAnalyzePage({
  required String imagePath,
  required OcrModelPaths models,
  required String ep,
  String? inpaintModel,
  String? erasedOutput,
  int? maxNewTokens,
}) => RustLib.instance.api.crateApiOcrOcrAnalyzePage(
  imagePath: imagePath,
  models: models,
  ep: ep,
  inpaintModel: inpaintModel,
  erasedOutput: erasedOutput,
  maxNewTokens: maxNewTokens,
);

/// 一个文本块。`quad` 是 8 个数（左上 / 右上 / 右下 / 左下，原图像素坐标）。
class OcrBlock {
  final Float32List quad;

  /// 按**列优先读序**拼好的原文（右→左、列内上→下）。
  final String text;

  /// 组成该块的检测框数量，用来判断这一块是否由多列拼成。
  final int boxes;

  /// 识别是否因达到上限被截断 —— 截断的文本应在上层标为可疑。
  final bool truncated;

  const OcrBlock({
    required this.quad,
    required this.text,
    required this.boxes,
    required this.truncated,
  });

  @override
  int get hashCode =>
      quad.hashCode ^ text.hashCode ^ boxes.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrBlock &&
          runtimeType == other.runtimeType &&
          quad == other.quad &&
          text == other.text &&
          boxes == other.boxes &&
          truncated == other.truncated;
}

/// 四个模型文件的路径。检测件与识别件分别来自各自的模型仓库，见 `REFERENCE_RESEARCH.md` §8.6.1。
class OcrModelPaths {
  final String det;
  final String encoder;
  final String decoder;
  final String vocab;

  const OcrModelPaths({
    required this.det,
    required this.encoder,
    required this.decoder,
    required this.vocab,
  });

  @override
  int get hashCode =>
      det.hashCode ^ encoder.hashCode ^ decoder.hashCode ^ vocab.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrModelPaths &&
          runtimeType == other.runtimeType &&
          det == other.det &&
          encoder == other.encoder &&
          decoder == other.decoder &&
          vocab == other.vocab;
}

/// 一页的分析结果。耗时字段的单位是毫秒。
class OcrPageResult {
  final List<OcrBlock> blocks;
  final int pageWidth;
  final int pageHeight;
  final BigInt detectMs;
  final BigInt recognizeMs;
  final BigInt inpaintMs;

  /// 擦干净的底图（仅在给了 `erased_output` 时写出）。译文要画在这张图上。
  final String? erasedPath;

  const OcrPageResult({
    required this.blocks,
    required this.pageWidth,
    required this.pageHeight,
    required this.detectMs,
    required this.recognizeMs,
    required this.inpaintMs,
    this.erasedPath,
  });

  @override
  int get hashCode =>
      blocks.hashCode ^
      pageWidth.hashCode ^
      pageHeight.hashCode ^
      detectMs.hashCode ^
      recognizeMs.hashCode ^
      inpaintMs.hashCode ^
      erasedPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OcrPageResult &&
          runtimeType == other.runtimeType &&
          blocks == other.blocks &&
          pageWidth == other.pageWidth &&
          pageHeight == other.pageHeight &&
          detectMs == other.detectMs &&
          recognizeMs == other.recognizeMs &&
          inpaintMs == other.inpaintMs &&
          erasedPath == other.erasedPath;
}
