// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_radial_config`, `radial_menu`

/// 解析一次输入事件 → 命中的动作 id（没人认领时返回 `None`）。
///
/// `contexts` 是当前**活跃**的 context 名（`reader` / `shell` / …），
/// 由 Dart adapter 报告 —— 只有应用自己知道现在在场的是哪块内容。
String? operationBindingResolve({
  required String bindingsJson,
  required String inputJson,
  required List<String> contexts,
}) => RustLib.instance.api.crateApiOperationBindingOperationBindingResolve(
  bindingsJson: bindingsJson,
  inputJson: inputJson,
  contexts: contexts,
);

/// 返回完整的命中绑定，供外壳执行动作序列及处理重复 / 长按。
/// 原始行随结果返回，保留 durationMs 等平台采集参数和扩展字段。
String? operationBindingResolveBinding({
  required String bindingsJson,
  required String inputJson,
  required List<String> contexts,
}) =>
    RustLib.instance.api.crateApiOperationBindingOperationBindingResolveBinding(
      bindingsJson: bindingsJson,
      inputJson: inputJson,
      contexts: contexts,
    );

/// 采集端的局部落点 → 九宫格；分区几何仍由核心唯一实现。
String? operationBindingAreaAtPoint({
  required double x,
  required double y,
  required double width,
  required double height,
}) => RustLib.instance.api.crateApiOperationBindingOperationBindingAreaAtPoint(
  x: x,
  y: y,
  width: width,
  height: height,
);

/// 把一条翻页动作解释成翻页语义：`"next"` / `"previous"`；不是翻页动作返回 `None`。
///
/// 这是**阅读方向唯一生效的地方**：`reader.page-right` 在右开（readMode≠2）下是
/// 下一页、在左开（readMode=2）下是上一页。`read_mode` 的取值与阅读页一致
/// （0 条漫 / 1 右开 / 2 左开；条漫按右开解释 —— 竖向没有左右）。
String? operationBindingResolvePageTurn({
  required String actionId,
  required int readMode,
}) => RustLib.instance.api
    .crateApiOperationBindingOperationBindingResolvePageTurn(
      actionId: actionId,
      readMode: readMode,
    );

/// 找出绑定表里所有冲突（同 `context + 输入` 上多于一条启用绑定）。
///
/// 返回 JSON 数组：`[{"key": "...", "bindingIds": ["a", "b"]}, …]`。
/// **冲突阻止保存**：由设置页挡在保存之前，而不是安静地取第一条。
String operationBindingConflicts({required String bindingsJson}) =>
    RustLib.instance.api.crateApiOperationBindingOperationBindingConflicts(
      bindingsJson: bindingsJson,
    );

/// 兼容旧版：九宫格点击绑定表（`right-hand` / `left-hand`），JSON 数组。
///
/// 预设绑的是**空间动作**（`reader.page-right` / `reader.page-left`），
/// 阅读方向在 [`operation_binding_resolve_page_turn`] 里解释 —— 方向换挡
/// 不需要重写绑定表。
String operationBindingTapPreset({required String preset}) => RustLib
    .instance
    .api
    .crateApiOperationBindingOperationBindingTapPreset(preset: preset);

/// 兼容旧版：键盘绑定表（用于识别和迁移旧默认值），JSON 数组。
String operationBindingKeyPreset() =>
    RustLib.instance.api.crateApiOperationBindingOperationBindingKeyPreset();

/// Neo 默认九宫格、滚轮、键盘、鼠标绑定，以及本仓默认轮盘槽位。
String operationBindingFactoryPreset() => RustLib.instance.api
    .crateApiOperationBindingOperationBindingFactoryPreset();

/// 未改动的旧默认输入表升级到 Neo 默认值；自定义配置返回 None，轮盘行原样保留。
String? operationBindingUpgradeDefaults({required String bindingsJson}) =>
    RustLib.instance.api
        .crateApiOperationBindingOperationBindingUpgradeDefaults(
          bindingsJson: bindingsJson,
        );

/// 动作注册表（`id` / `label` / `category` / `categoryLabel` / `implemented`），JSON 数组。
///
/// 设置页的选项清单从这里取 —— Dart 侧不抄第二份「有哪些动作、哪个能用」（ADR-0015）。
String operationBindingActionCatalog() => RustLib.instance.api
    .crateApiOperationBindingOperationBindingActionCatalog();

/// 这份 JSON 是不是**合法**的绑定表（数组或裸数组都算，解析不了返回 `false`）。
///
/// 存在的理由：上面几个函数对不合法的输入直接 `expect`（那是「调用方已经校验过」的前提）。
/// 绑定表要落进用户设置、还要吃用户导入的文本，所以校验这一步必须**能失败**而不是
/// 让 Rust 侧 panic —— 每次点击都跨一次桥，崩在这里等于阅读器整体打不开。
bool operationBindingValidate({required String bindingsJson}) =>
    RustLib.instance.api.crateApiOperationBindingOperationBindingValidate(
      bindingsJson: bindingsJson,
    );

/// 轮盘的出厂文档（默认轮盘：3 层 · r120 · 内 40 · 起始角 -90 · 扫过 360），JSON。
String operationBindingRadialDefaultConfig() => RustLib.instance.api
    .crateApiOperationBindingOperationBindingRadialDefaultConfig();

/// 这份轮盘文档**读得懂且合法**吗（吃用户设置与用户导入，所以校验要能失败而不是 panic）。
bool operationBindingRadialValidate({required String configJson}) =>
    RustLib.instance.api.crateApiOperationBindingOperationBindingRadialValidate(
      configJson: configJson,
    );

/// 轮盘文档的问题清单（人话，JSON 数组；空数组 = 可用）。
///
/// 与 [`operation_binding_radial_validate`] 分开是两个用途：validate 给保存路径当闸门，
/// problems 给设置页当说明 —— 「不许保存」得配上「为什么」。
String operationBindingRadialProblems({required String configJson}) =>
    RustLib.instance.api.crateApiOperationBindingOperationBindingRadialProblems(
      configJson: configJson,
    );

/// 一个轮盘显示出来的全部槽位（**含空格**），JSON 数组。
///
/// 外壳**照着这份数字画**：每格的内外半径、起止角、标签、能不能选，都在里面。
/// 命中判定读的是同一组数字（见 [`operation_binding_radial_slot`]），所以
/// 「高亮的一格」与「执行的一格」不可能是两格。
String operationBindingRadialLayout({
  required String configJson,
  required String menuId,
}) => RustLib.instance.api.crateApiOperationBindingOperationBindingRadialLayout(
  configJson: configJson,
  menuId: menuId,
);

/// 落点（相对圆心的偏移）→ 选中的槽，返回 `RadialSlotHit` 的 JSON
/// （`menuId` / `itemId` / `level` / `index` / `legacyAction` / `moveToMenuId`）。
///
/// 外壳拿 `itemId` 拼出那条 `radial` 输入去问解析器；`legacyAction` 是 neoview 的
/// 回落（老包里条目自己带动作、而绑定表里没有那一行时用它），`moveToMenuId` 非空
/// 表示这一格是「跳转轮盘」，松手换轮盘而不是执行动作。
/// 落在空洞、空格、被禁用的条目或扫过角之外 ⇒ `None`。
String? operationBindingRadialSlot({
  required String configJson,
  required String menuId,
  required double dx,
  required double dy,
}) => RustLib.instance.api.crateApiOperationBindingOperationBindingRadialSlot(
  configJson: configJson,
  menuId: menuId,
  dx: dx,
  dy: dy,
);

/// 某个轮盘的出厂槽位绑定（只有默认轮盘有；新轮盘返回空数组），JSON 数组。
String operationBindingRadialPreset({required String menuId}) => RustLib
    .instance
    .api
    .crateApiOperationBindingOperationBindingRadialPreset(menuId: menuId);

/// 新建一个轮盘（设置页的「新轮盘」），JSON。
///
/// id 与名字的生成规则归核心：与 [`operation_binding_radial_default_config`] 同一处，
/// 免得外壳自己拼一套而与核心 `prune_bindings` 认的 id 分叉。
String operationBindingRadialNewMenu({required int count}) => RustLib
    .instance
    .api
    .crateApiOperationBindingOperationBindingRadialNewMenu(count: count);

/// 新建一个条目的 id（`item-N`，neoview 的 `uniqueId("item", …)`）。
String operationBindingRadialNewItemId({required int count}) => RustLib
    .instance
    .api
    .crateApiOperationBindingOperationBindingRadialNewItemId(count: count);

/// 轮盘形状变了之后，剪掉指向**已不存在的条目**的那些绑定，返回留下的绑定（JSON 数组）。
///
/// 剪的只有 `input.device == "radial"` 且 `(menuId, itemId)` 已经画不出来的行；
/// 键盘、鼠标、点击、滚轮一条都不许动。
String operationBindingRadialPrune({
  required String configJson,
  required String bindingsJson,
}) => RustLib.instance.api.crateApiOperationBindingOperationBindingRadialPrune(
  configJson: configJson,
  bindingsJson: bindingsJson,
);
